### ISSUE TITLE
Elytra Mode For Jetpacks

### ISSUE THREAD

**Issue by brianSites** [mekanism/Mekanism-Feature-Requests#103]
I would like to request an elytra mode be added to jetpacks. This will function similarly to normal elytras but you use hydrogen to boost yourself instead of fireworks. To activate it, press space after jumping from a height. To boost, press space while in flight. This  will consume some fuel to boost your speed. Holding space will boost over an extended period of time but consume fuel every second. This will make traveling via jetpack much more fun and faster.

**Comment by csonyi** [comment]
Mekasuit Elytra mode would be awesome!
I can also imagine some sort of firework-like booster upgrade to the meka-tool, so you wouldnt have to carry firework rockets in your inventory
