### ISSUE TITLE
"Set all sides to empty" button

### ISSUE THREAD

**Issue by BentoGambin** [mekanism/Mekanism-Feature-Requests#109]
It would be awesome, for using the configurator, if every ui connection category (gas, fluid, energy,pigment,heat...) had a button tucked to the corner that once pressed set all of the sides (up, down, front, back, left, right), on it's category only, to "none". 
A clear and concise description of what you want.

**Describe alternatives you've considered**
Maybe a client config (that's off by default) that every placed machine will have all sides set to none by default, allowing for easier setup using the Configurator.
Maybe like this?
Thanks for the awesome mod!
![image](https://user-images.githubusercontent.com/41645690/92664246-db57a280-f2d9-11ea-8a80-fbb2dcdb6cd3.png)

**Comment by pupnewfster** [comment]
This sounds like a decent idea and if I remember I will probably include it among other QoL changes for Mek 10.1

**Comment by BentoGambin** [comment]
Cool! :D

**Comment by BentoGambin** [comment]
I've been thinking about this and the more I think, the more the "_client config that every placed machine will have all sides set to none by default_" seems to be the best. The reasoning for that is when cramming machines next to one another there would be no accidents on gases going where they shouldn't, pipes wrongly connecting, etc. That's not to say that the gui button is not a good idea, of course!

**Comment by andrewsf** [comment]
If it helps -- it took me a couple weeks to realize that you can hold Shift and click a slot to set it straight to None without cycling through all the options.

**Comment by BentoGambin** [comment]
WHAT? How have I not found out about it? That's actually really useful, thanks!
