### ISSUE TITLE
Add another frequency menu for Trusted MC 1.16.3

### ISSUE THREAD

**Issue by litjohn50** [mekanism/Mekanism-Feature-Requests#125]
**Describe the the feature you'd like**

When you are making a frequency you either have 2 options. Give everyone access or only yourself. This really hurts co-op play (Examples will be in additional context). 

So I was thinking that having another tab in the frequency setting menu for trusted players. This will allow co-op teams to have access to something like the QIO system for wireless connection, aswell as the quantum Entangloporter.

**Describe alternatives you've considered**

There is an alternative by enabling trusted players to have access to your private frequency list, but I don't think most people would want having trusted to give perms to everything even stuff you want private.

**Additional context**

Examples:
The Additional tab would be here located next to or in the middle of the already existing tabs.
https://cdn.discordapp.com/attachments/760356190445895690/768287706383908874/unknown.png

Changing the machine to trusted does not change the frequencies added.
https://cdn.discordapp.com/attachments/760356190445895690/768288692716306442/unknown.png

**Comment by Peekofwar** [comment]
Would be cool if there was a way to set the teleporter to a public "unlisted" frequency which would work like direct connecting to a server by IP, except it's just an ID that you set.

**Comment by JAWalmsley** [comment]
Really hope this idea works out, or possibly the ability to share a frequency with just one person.

**Comment by Peekofwar** [comment]
> Really hope this idea works out, or possibly the ability to share a frequency with just one person.

 Would be cool if you could also create categories and set the publicity... For example, I could have my private category contain personal affects, and have a company category set to trusted, so that all players placed into my Security Station whitelist could see all "Aedificate Co." related frequencies. 

This would be a little more advanced, but it would be cool if you could setup groups and share machines and frequencies with specific groups of players.

**Comment by FlickCZ** [comment]
I would like to see this feature in the newer version of mc too

**Comment by Brecony76** [comment]
Has this been implemented yet?

**Comment by RandomGlitchhunter** [comment]
@pupnewfster Can you guys port this to 1.16.5?

**Comment by Peekofwar** [comment]
> Has this been implemented yet?

I personally haven't seen the feature. I didn't see it in the latest version of Mekanism for 1.20.1.

I only see an option for Public and Private in Mekanism version 10.4.15. Minecraft 1.21 was released about four months after this was marked as "completed." So unless they withheld this feature and waited until 1.21... I'm not sure.

<img width="644" height="498" alt="Image" src="https://github.com/user-attachments/assets/a19cbb52-dabc-4f58-b77e-8db7439feed1" />
