### ISSUE TITLE
Configuration card functionality extensions

### ISSUE THREAD

**Issue by Letoric** [mekanism/Mekanism-Feature-Requests#133]
**Describe the the feature you'd like**
Currently, the configuration card is only capable of copying configurations from machines that are identical, including tier. It would be fantastic if they could:
1) Work with machines of the same type, without requiring the same tier, since the port configuration is generally the same across tiers.
2) Work with chem tanks, as copying the port configuration there would be very useful.

**Describe alternatives you've considered**
Currently for machines, I manually configure 1 for each tier before I can start copying. For chem tanks, I have to manuallyi configure all of them.

**Comment by Seniorendi** [comment]
Nice!

**Comment by WesCook** [comment]
I'd like to add that my preferred machine configuration is to start blank.  I hoped I could use the card to "zero out" the machines, before customizing them for a specific use.  Unfortunately the limitations on the card do not allow this.  I'd love to see the configuration card upgraded to be more compatible across machine types.

My suggestion would be to change the interaction so it opens its own GUI window, and that would allow you to set item/gas/power/slurry/etc inputs and outputs for each side.  When applied to a machine, it would simply accept whatever values are applicable for that machine type.

A new option of "no change" would also be useful in this system, to prevent overwriting any existing side information.
