### ISSUE TITLE
Crafting with QIO storage.

### ISSUE THREAD

**Issue by JesGudiksen** [mekanism/Mekanism-Feature-Requests#161]
Hi.

Some kind of CraftingTable / Crafting station attached to your QIO Storage, so you can craft with items directly in your storage.

**Comment by OfflinePing** [comment]
@pupnewfster when the update will be out?

**Comment by pupnewfster** [comment]
No idea and asking for updates is a rather impolite thing to do in general. Hopefully in a couple months but maybe longer no idea...

**Comment by orchidalloy** [comment]
I'm waiting on this to start a new game
