### ISSUE TITLE
Add a way for modpack authors to configure the maximum fission fuel burn rate in a reactor in the config file.

### ISSUE THREAD

**Issue by Gliese-832-c** [mekanism/Mekanism-Feature-Requests#170]
I'm making a small Mekanism-based modpack right now, and one thing I noticed during playtesting is that fission fuel consumption is pretty fast and quite unrealistic. So I went into the config file to increase the energy production from fissile fuel, but decrease the maximum burn rate by the same factor, so reactors produce an identical amount of energy, but from less fuel. The problem is: The energy production config option exists, but a maximum burn rate option doesn't. So I hereby kindly request the addition of such a config option to make the lives of modpack authors like me easier.

**Comment by pupnewfster** [comment]
I added a couple configs related to this that are included in 10.0.20
