### ISSUE TITLE
Quantum entangloporter Channel confirmation on delete

### ISSUE THREAD

**Issue by willcheat** [mekanism/Mekanism-Feature-Requests#187]
When setting a QE on a channel, it's way too easy to derp and click DELETE instead of SET because of muscle memory. It would be really appreciated if the channel deletion came with a confirmation pop-up, in order to lower the amount of time one has to run around 8 different dimensions to re-set their energy channels on all their stuff.

**Comment by pupnewfster** [comment]
In theory this should be relatively easy to do because we implemented something similar for QIO frequencies, but not sure if I will get around to doing so before 10.1.0.
