### ISSUE TITLE
/Suggestion

### ISSUE THREAD

**Issue by oooooo135** [mekanism/Mekanism-Feature-Requests#201]
I have 2 one is to have transport tubes similar to the ones from thermal dynamics as those are getting removed from thermal dynamics, and the other is for a better version of the digital miner it mines from the void and will mine random resources but ill require a digital miner to craft and other high end materials, such as some anti-matter

**Comment by pupnewfster** [comment]
> one is to have transport tubes similar to the ones from thermal dynamics as those are getting removed from thermal dynamics

As someone who has never used thermal dynamics this is beyond vague

> other is for a better version of the digital miner it mines from the void and will mine random resources

No

**Comment by Silfryi** [comment]
I think they mean viaducts, which were like sticking a player in the P2 pneumatic delivery system if you're ever played P2, and if not here's a wiki link. https://teamcofh.com/docs/1.12/thermal-dynamics/viaduct/

**Comment by pupnewfster** [comment]
Personally I don't think that really has a place in Mekanism, given we have teleporters and stuff, so going to go ahead and close this then.
