### ISSUE TITLE
Suggestion: Digital Miner Filter

### ISSUE THREAD

**Issue by Jarvis2005** [mekanism/Mekanism-Feature-Requests#202]
I suggest to add an "except" option to Tags filter in Digital Miner. So that I can Coal Ore to except in the "forge:ores" filter and it will mine all ores except coal. Because coal is filling up my personal chest and inventory of Digital Miner. I have to empty it time to time.

**Comment by pupnewfster** [comment]
Duplicate of #173 so going to merge tracking of this into that one
