### ISSUE TITLE
[Request] Cobble generator upgrade for digital miner

### ISSUE THREAD

**Issue by dashkal16** [mekanism/Mekanism-Feature-Requests#219]
Feature Request: An upgrade to add to the digital miner that allows it to replace with cobblestone without the need for cobblestone in the inventory.

The purpose is to allow easy access to filling simply to avoid flowing liquid or small spawn holes.

**Comment by pupnewfster** [comment]
Already planned for 10.1 with the exception of the fact it will be a stone generator rather than a cobblestone generator.

**Comment by bshelden** [comment]
Awesome!

**Comment by nuggetcatsoftware** [comment]
nice
