### ISSUE TITLE
Feature Idea, Monitor/displays show info about machines.

### ISSUE THREAD

**Issue by icebolt9000** [mekanism/Mekanism-Feature-Requests#23]
**Describe the the feature you'd like**
a monitor that displays power and info about Induction Matrix and other machines

**Describe alternatives you've considered**
not sure what other way you can display info than monitor.

**Additional context**
![image](https://user-images.githubusercontent.com/58339767/73806188-11bfc300-47c9-11ea-87ac-47e60d3e00bd.png)
used computercraft but for idea.

**Comment by Seniorendi** [comment]
This issue can be closed because of https://github.com/mekanism/Mekanism/issues/6445
@pupnewfster

**Comment by pupnewfster** [comment]
I mean I am pretty sure the idea of this issue is to make a monitor that can display it without the need for other mods.

**Comment by Seniorendi** [comment]
Ahh yes

**Comment by SirEndii** [comment]
Okay?
