### ISSUE TITLE
Add a config to disable Flamethrower destroying items.

### ISSUE THREAD

**Issue by ianlavr** [mekanism/Mekanism-Feature-Requests#236]
Config to disable Flamethrower destroying items would be very nice since Flamethrower can destroy valuable drops from mobs and bosses and in general Flamethrower destroying items is very annoying.

**Comment by pupnewfster** [comment]
I am adding a config for this in 10.1, but I think I am going to make it still attempt to smelt the item first and then just not destroy it afterwards if it can't instead of also not smelting the item.
