### ISSUE TITLE
Dyeable MekaSuit

### ISSUE THREAD

**Issue by ElSkybox** [mekanism/Mekanism-Feature-Requests#239]
It would be cool if you could dye/paint the mekasuit like you could a piece of leather armor.
I propose a system where you are able to place a minecraft dye and a MekaSuit armor into the modification station to paint the white /black sections of the armor a different color. If this isn't viable due to coding issues, the normal crafting would probably suffice.

If you don't want to stop there, you could even make a system to apply the texture of any block to the mekasuit (though this would be a much more complicated ordeal than simple dyes.

**Comment by pupnewfster** [comment]
#72
