### ISSUE TITLE
Formulaic Assemblicators should automatically move crafting formula's to crafting formula slot

### ISSUE THREAD

**Issue by quinchs** [mekanism/Mekanism-Feature-Requests#246]
## Summary
Formulaic Assemblicators should take any incoming encoded crafting formulas coming through an item input and move them to their slot. This would make automation alot nicer (especially for CC).

Currently the encoded formulas just go to the crafting slots, It would be nice to see them go to the formula slot.

**Comment by pupnewfster** [comment]
If I remember I may look at this for 1.17 but with how our slots are implemented I don't think it is really possible to implement before then without causing all sorts of issues with loading existing formulaic assemblicators.
