### ISSUE TITLE
Add indications on burnable gases

### ISSUE THREAD

**Issue by Yodirr** [mekanism/Mekanism-Feature-Requests#247]
I've got a suggestion, tell me if i'm wrong but i think it's mentioned nowhere (or not easily) that gas burning generator can burn oxygen and ethylene (i discovered ethylene after making my first fusion reactor lol). It could be cool if it was written on the gas burning generator tooltip.

Another alternative i have is to mark/tag those gases as "burnable".

**Comment by pupnewfster** [comment]
The way I ended up going with in https://github.com/mekanism/Mekanism/commit/a18c9667f4b7b6ae56fb1f8ca8961078aed34472 was to just add it to the tooltips of the gases as JEI's tooltip search then should be able to find the things well enough.

![image](https://user-images.githubusercontent.com/1203288/128639158-b8d9e0b1-3b8e-455b-bb5a-2cbc9f71e663.png)
