### ISSUE TITLE
Biome Module

### ISSUE THREAD

**Issue by MegaGamer265** [mekanism/Mekanism-Feature-Requests#264]
### Describe the feature you'd like

It would be amazing if we can change biome with the Meka-Tool. Just rightlick on the biome you want and place it with leftclick.

**Comment by pupnewfster** [comment]
This does not really seem like something that fits into how Mekanism does things so I am going to close this. That doesn't mean that an addon can't do something like this though if they wanted to (at least once Mekanism 10.1 is released as that adds support in for custom modules).
