### ISSUE TITLE
Reversed Fluidic Plenisher

### ISSUE THREAD

**Issue by Iluminatiko44** [mekanism/Mekanism-Feature-Requests#266]
### Describe the feature you'd like

So the basic idea is that you have a reversed Fluidic Plenisher that removes/pumps the source block of water and starting from the most outer radius this may be possible.

### Describe alternatives you've considered

It could also be like a switch, like in the Rotary Condensator, that is in the GUI of the Fluidic Plenisher.

### Additional context

This could be helpful for getting water out of a monument or an underwater base, just like sponges but in much better ;)

**Comment by thiakil** [comment]
You can do that with the Electric Pump, the config option is just disabled by default because of how MC's water works / performance
