### ISSUE TITLE
QIO "Interface" to Connect other Storage Systems

### ISSUE THREAD

**Issue by Tris-Barlok** [mekanism/Mekanism-Feature-Requests#274]
### Describe the feature you'd like

The functions of QIO are currently quite limited, especially in autocrafting.

Therefore, a kind of interface would be great where you can e.g. the "External Storage" module from refined storage or similar ("Storage Link Cable" from Simple Storge, "ME Storage Bus" from AE2 etc.) can be connected.

**Comment by AlexHgC** [comment]
Message from the FAQ on the discord : 

![image](https://user-images.githubusercontent.com/31996023/126882941-677ff9b9-f248-43dc-8df6-fa168129b020.png)
