### ISSUE TITLE
Allow Jetpack to function from Curio slots

### ISSUE THREAD

**Issue by nerdywhiteguy** [mekanism/Mekanism-Feature-Requests#284]
### Describe the feature you'd like

I was able to add the Jetpack to `<tag:items:curios:back>`, which worked and allows me to wear the Jetpack there. However, the Jetpack does not function while worn there. (Nothing is added to the HUD and holding space doesn't let you fly.)

I saw #169, but that request was about two things, and didn't go into much detail about either.

To be clear: I am **just** requesting for the Jetpack to **function** from a Curio slot. I am **not** requesting it to be wearable there by default. This feature request is mainly aimed at providing pack authors additional flexibility.

### Describe alternatives you've considered

While the Armored Jetpack is indeed a nice solution to the problem of not having armor on your chest, and the Armored Jetpack is "better" than most other chestplates, the Armored Jetpack can't be enchanted.

While a mod like [Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked) could make it visually appear that you're wearing some other chestplate while actually wearing the Jetpack, the "functional" armor (the Jetpack) still can't be enchanted.

Additionally, the Armored Jetpack doesn't take damage when you're hurt, unlike most chestplates, meaning that you now have a *very* tough chestpiece that doesn't wear out or require Mending to fix.

I'm not looking to "invalidate" the Armored Jetpack at all, or to make it "useless". Especially in the default configuration! But it would be nice if pack authors had some more configuration flexibility. (For example, I'm considering making the Armored Jetpack more of an "end game" item since, as it stands, the one "correct" chestpiece to be wearing is the Armored Jetpack. Forcing the player to make some more choices about what armor they wear instead of just having one "correct" answer is appealing to me.)

I understand that allowing the Jetpack to be worn in a Curio slot *by default* may not be desirable, but if the user has configured it to be wearable there, it would be nice if it functioned as expected.

### Additional context

Minecraft 1.16.5

**Comment by Matyrobbrt** [comment]
https://github.com/mekanism/Mekanism/pull/7446
