### ISSUE TITLE
A gas tank muliblock

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism-Feature-Requests#285]
### Describe the feature you'd like

i would like a gas tank multiblock that can hold gases and sluries and could hold the same amount as a dynamic tank per size just for gases 

### Describe alternatives you've considered

you could also make the dinamic tank to also hold gases or make any tipe of gas/slury liquifible (for example liquid nutritional paste)

### Additional context

i runed into the problem of wanting to store alot of nutritional paste but the ultimate gas tanks coultn cut it

**Comment by pupnewfster** [comment]
V10 already allows you to store chemicals in the dynamic tank (10.1 will fix the fact that it has the same storage size for chemicals as fluids)
