### ISSUE TITLE
Mekanism Security: QIO/Teleporter/QE frequency categories

### ISSUE THREAD

**Issue by atlgeek007** [mekanism/Mekanism-Feature-Requests#286]
### Describe the feature you'd like

Having just public/private frequencies for teleporters, QIO, and Quantum Entangloporters is limiting a bit.  It would be nice if Mekanism frequencies could take advantage of "trusted" players via the security desk and add a third channel category, or possibly integrate with mods like FTBTeams to provide a "Teams" frequency set.

For instance, allowing people I "Trust" to use my QIO storage via remote terminals, or access my teleporter or quantum entangloporter frequencies would be nice.

**Comment by pupnewfster** [comment]
Duplicate of #125
