### ISSUE TITLE
Logistical Sorters should be able to get fed by logistical transporters

### ISSUE THREAD

**Issue by Compaszer** [mekanism/Mekanism-Feature-Requests#293]
### Describe the feature you'd like

I would love, if logistical sorters could be attached to a logistical transporter and would be able to sort items fed by the logistical transporter. In this way it would be much easier to make a system sorting you items.

### Describe alternatives you've considered

To achive the same effect you could feed your items into hoppers and attach the logistical sorters to the hoppers. The main problem with this solution is, that the sorters sometimes miss an item, so you need a feedback loop at the end to ensure that every item will be sorted in the end. Of course it takes much longer (4x longer I believe) until all items are sorted and the contraption is much larger (and more expensive).

**Comment by AlexHgC** [comment]
If i understand correctly what you want, i have to tell you something : you already can sort items with logistical sorter and transporter. First, on the sorter, create filter and set a color like green. Now, connect transporter to the chest you wan, and use a configurator on the transporter on the chest to make it green. Now, all items with green filter will go on the green transporter. If you want, you can set the sorter to only send items with filter

**Comment by pupnewfster** [comment]
With how the systems work this is not going to happen (though 10.1 dose make it so it doesn't attach on the back to help prevent people get confused). Just use a chest in the middle if you need to start sorting things.

**Comment by Compaszer** [comment]
Thanks a lot, did't thought about using a chest in between to expand my sorting capabilities.
