### ISSUE TITLE
Fluorite Block

### ISSUE THREAD

**Issue by AR-E** [mekanism/Mekanism-Feature-Requests#297]
### Describe the feature you'd like

A fluorite block.

### Additional context

Fluorite ore behaves similarly to redstone ore, and yet has no storage block. This makes mining it a pain (it fills up storage fast), so I think it would be really helpful if a block version of it existed.

**Comment by beholderface** [comment]
One workaround is to bring a bin with you when mining, and just chuck the crystals in there. 
And by the time you need to use fluorite in most packs, you should already have the capacity to make a digital miner which can eject the fluorite straight into the bin.

**Comment by pupnewfster** [comment]
To add on to that you in theory should be able to combine the bin and a stack of fluorite in your crafting grid without having to place the bin down first. Though I don't think it is necessarily a bad an idea to potentially add a fluorite block as a storage block at some point.

**Comment by kingdevnl** [comment]
I'm working on a PR to add a fluorite block.
