### ISSUE TITLE
Cables through walls

### ISSUE THREAD

**Issue by MegaGamer265** [mekanism/Mekanism-Feature-Requests#298]
### Describe the feature you'd like

Cables should somehow be able to go through walls like immersive engineering or futurepack. So we don`t have these nasty holes in the wall of our buildings!

**Comment by pupnewfster** [comment]
Closing this as it is more or less a duplicate as the concept of either of these requests:
https://github.com/mekanism/Mekanism-Feature-Requests/issues/89
https://github.com/mekanism/Mekanism-Feature-Requests/issues/114
