### ISSUE TITLE
Enchantments for the Mekasuit

### ISSUE THREAD

**Issue by Eric9922** [mekanism/Mekanism-Feature-Requests#307]
### Describe the feature you'd like

I think enchantments for the meka suit would be great. Perhaps an enchanting module could be added that would make it possible to enchant the armor.

**Comment by pupnewfster** [comment]
There are no plans to make the Mekasuit enchantable. 10.1 will bring the ability for addon developers to create custom modules if they want to reimplement specific enchantments but it is intentionally unenchantable.
