### ISSUE TITLE
A new Pipe type

### ISSUE THREAD

**Issue by Eric9922** [mekanism/Mekanism-Feature-Requests#308]
### Describe the feature you'd like

A new type of pipe. Craftable with antimatter, which can conduct energy infinitely or almost infinitely.

**Comment by SirEndii** [comment]
Would be interesting
But with the current transmitter system hard, the pipes would store *a lot* of energy. So it's like a tank, and that is not the purpose of a cable.

**Comment by Eric9922** [comment]
Too bad. But you couldn't store so much energy in these improved pipes. Then they would be more like a cable and it would make sense to the Antimatter.

**Comment by AlexHgC** [comment]
But that's not how cables works. Rate = buffer size. If you want like 16,000,000,000 rate, you need to have 16,000,000,000 buffer.
Actual cable buffer on V10 are already too OP ( will be nerfed on V10.1 ). 

But don't forget : Pull rate **isn't** cable rate. Cable rate is the same than cable buffer. So, ultimate are really fine

**Comment by Eric9922** [comment]
And why isn't it possible to add a new type of cable that doesn't?

**Comment by SirEndii** [comment]
It's possible with a lot of effort
So maybe this will be a thing in late future versions, but not before the cables in mekanism gets a remake

**Comment by Eric9922** [comment]
ok, thanks. It would be great.
