### ISSUE TITLE
Improve item auto-eject algorithm (randomize slot order)

### ISSUE THREAD

**Issue by BentoGambin** [mekanism/Mekanism-Feature-Requests#31]
I'll try to explain as best as I can, but it's a very weird bug:
First of all, my setup:
![2020-04-27_18 13 14](https://user-images.githubusercontent.com/41645690/80422296-4f0d8b80-88b4-11ea-8336-af223b2fbad7.png)
As you can see, I have a 4x ore processing. The gold seem to have a lower priority or something in the auto-eject functionality. If i'm processing just gold by itself it works flawlessly, but if there's any other metal being processed it will "take over". 
As you can also see in the image, there's dirty gold dust to export in the crusher AND theres space in the enrichment chamber, but only the copper exports normally, backlogging the gold. 

EDIT: Enabling and disabling redstone control quickly fixes the system. But it will still happen afterwards

#### Steps to reproduce:
I'm not sure if it can be reproduced reliably.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  31.1.46
**Mekanism:**  9.10.1
**Other relevant version:** MC 1.15.2
Thanks!

**Comment by aidancbrady** [comment]
I've implemented the fix mentioned above in our v10 branch.
