### ISSUE TITLE
[Feature Req] Permanent radioactive storage & Dynamic Tank for Gases

### ISSUE THREAD

**Issue by zappermax** [mekanism/Mekanism-Feature-Requests#311]
### Describe the feature you'd like

**Permanent radioactive storage**
Basically, a waste barrel that doesn't decay contents.

Why? Because anything other than spent waste is useful.

I don't care if it's not portable tbh.

----------------
**Dynamic Tank for Gases**
Would be great to use, especially as a buffer for overkill reactors.

### Describe alternatives you've considered

**Permanent radioactive storage**
Could be used in the dynamic tank I've just suggested

----------------
**Dynamic Tank for Gases**
Instead of making a separate dynamic tank for gasses, why not use the same one for either?

### Additional context

I don't think this is needed but feel free to ask if what I'm suggesting doesn't make sense.

**Comment by SirEndii** [comment]
You can already store gases in dynamic tanks

**Comment by AlexHgC** [comment]
And Waste Barrel already only decay spent waste iirc

**Comment by SirEndii** [comment]
Nah they decay everything

**Comment by zappermax** [comment]
Oh dynamic tanks can store gases? Since when

**Comment by SirEndii** [comment]
Since there exists, I think
I used them in 1.12 and 1.16 to store gases

**Comment by AlexHgC** [comment]
No, waste barrel don't decay Polonium and Plutonium with default config since 10.0.18

**Comment by zappermax** [comment]
But it does decay regular waste

**Comment by AlexHgC** [comment]
And 1.12 dynamic tanks can't store gases, only fluid

**Comment by AlexHgC** [comment]
> But it does decay regular waste

You can process it instantly and store polonium

**Comment by zappermax** [comment]
That’s true actually.
I might as well close this issue as the whole thing was just me being small brain.
