### ISSUE TITLE
Have ALL Mekanism multiblocks turn OFF on sever start.

### ISSUE THREAD

**Issue by zookeper** [mekanism/Mekanism-Feature-Requests#315]
### Describe the feature you'd like

I would like for all of mekanism multiblocks to not start up automatically on a restart or crash Especially the Fission reactor. No logic input either, the input needs to be manual, maybe by accessing it as an entity? (opening a machine would allow it to be turned on or auto started if redstone logic is applied) and automatically turned off at the beginning of each server start.

### Describe alternatives you've considered

I have considered not playing ATM 6 simply because you need antimatter to progress and I have not intended to rebuild my reactor 8 times on an unstable public server for atm 6 modpack because the reactors constantly melt down on restart regardless of what's even hooked to them. This leads to serious issues when you have so many mods installed. For example your pipes cause lots of lag on multiplayer servers when everyone is using them so most server hosts have them disabled forcing players to use other means like pipez mod.

### Additional context

Fission reactor shouldn't be melting down on a restart or crash, ever. If sodium cooled is setup right with enough in it and the boiler with adequate transfer rate and the energy storage doesn't get full.....

A reactor is off and has fuel in it. Should it be on fire and melted down on restart or crash? this is happening every single crash so you can imagine what that's like with this many mods on a public server trying to get atm star literally to build a decorative castle and then leave the server.... I have literally everything made and ready to go but your antimatter.

I am sick and tired of rebuilding this reactor just to produce sps to get antimatter simply because of this CAVATE.

two weeks of my playtime have been struggling with this meltdown bs. in a total of a month playtime.

Did I mention I was making atm stars right and that I have everything but what's needed in your mod. your mod alone.

In an entire pack with hundreds of other peoples work in it? Was this an intended feature? maybe I should fill out a bug report. Well. I seee that there already bug reports about this issue so here goes nothing.

**Comment by NullPointerCollection** [comment]
What's a cavate?

**Comment by thiakil** [comment]
No

**Comment by SirEndii** [comment]
I would recommend using the logic adapter blocks to control your reactor to prevent things like this.
But I also never had these issues on my server with the same modpack. Try reaching out the server admin, maybe he's doing something stupid with a mod or the server chunks itself.

**Comment by zookeper** [comment]
What the hell? my reactors have logic they still melt down anyway.....

**Comment by zookeper** [comment]
The reactors are turning on every restart. and it's not the server owner that is the cause of it.

The fact that mekanism multiblocks exhibit all these other issues within itself...


And you have the audacity to come here and type "maybe your logic is wrong, maybe it's your server owner"

Look bud how many years has this reactor been melting down and exhibiting these issues? 

I post this feature request because im sick of dealing with it. I been playing this crap for years. The server im on right now isnt the only server this happens on so why even suggest that. you just make yourself look like a fool.

**Comment by zookeper** [comment]
for god sake. pipes wont even connect for most people. i mean. look at your bug reports.

**Comment by zookeper** [comment]
It wouldn't bother me if your mod was removed from all future atm packs entirely. and this is specifically due to the crap i have to deal with over these SEVERAL YEARS and on multiple different servers, multiple different versions.

**Comment by zookeper** [comment]
If you look close enough in the source code you can see that it was intentional thats why this is a feature request not a bug report.

**Comment by zookeper** [comment]
TBH i preferred gregtech fusion over this any day. i didnt care how long it took to get. it's not blowing it self up? Every god damn time.

**Comment by SirEndii** [comment]
You should definitely calm down… 

> It wouldn't bother me if your mod was removed from all future atm packs entirely. and this is specifically due to the crap i have to deal with over these SEVERAL YEARS and on multiple different servers, multiple different versions.

Several years? Mekanism's new reactor does only exist for almost a year and a half at this point.

> If you look close enough in the source code you can see that it was intentional thats why this is a feature request not a bug report.

You should show code if you say something like that.

> for god sake. pipes wont even connect for most people. i mean. look at your bug reports.

Connect to what? The only known issue that has to do with not connected pipes is that pipes are currently not connecting to composter.

You should start bringing facts instead of yelling at the mekanism developers who have also a life.

**Comment by NullPointerCollection** [comment]
Your setup must be bad if it's not working. I, and most others, don't have these issues. Since you're clearly not able to handle the pressure of a challenge, you probably should leave Mekanism alone.

**Comment by thiakil** [comment]
If you have issues with your setup that you think is a bug, you should post a bug report, not a ranty feature request to change stuff that sounds (in summary form at least) like it would require _everyone else_ to have to touch their reactors post-restart
