### ISSUE TITLE
Compatibility with controllable mod so I could fly using a usb controller instead of needing to use keyboard?

### ISSUE THREAD

**Issue by kyuMomo** [mekanism/Mekanism-Feature-Requests#316]
### Describe the feature you'd like

Is there a way to make it so I could fly by pressing a button on my controller?  The controllable mod author mentioned what the issue was:  https://github.com/MrCrayfish/Controllable/issues/97

### Describe alternatives you've considered

Creative mode works on controller: Flying is activated by double tapping the jump button. Maybe having an option like that in the config or something? 

### Additional context

I find playing with controller more comfortable for my hands. I find the keyboard controls very uncomfortable.

**Comment by pupnewfster** [comment]
So I looked into this, and it was simple enough to do for the jetpack. The one side effect I noticed is that it makes the jetpack activate if autojump activates, though I don't think that is necessarily a terrible thing given many people have auto jump disable and use various autostep mods instead.

**Comment by kyuMomo** [comment]
Thank you so much!

**Comment by pupnewfster** [comment]
We keep issues open, but labeled until the version it is implemented is released.

**Comment by kyuMomo** [comment]
Oh, ok, sorry about that! I wasn't sure.

**Comment by kyuMomo** [comment]
And again:  thank you SO MUCH!  :D
