### ISSUE TITLE
Implement a non-destructive "meltdown" alternative

### ISSUE THREAD

**Issue by stevenhay** [mekanism/Mekanism-Feature-Requests#317]
### Describe the feature you'd like

Currently, the two options are either:

1. Enable meltdowns and have the possibility of your reactor blowing up and damaging nearby structures, thereby forcing you to rebuild
2. Disable meltdowns and have _nothing_ happen when the temperature and damage become critical.

I'd like to propose a third option in which the reactor simply shuts down after reaching a configurable damage percentage as right now with meltdowns turned off, you can simply keep the reactor running and producing power even if you can't properly cool it.

**Comment by pupnewfster** [comment]
I agree this probably would be smart but I have a few questions that I might as well get your opinion on:
- Should I cap such a config option at 100% or higher? Given how meltdowns currently work is that there is a percentage chance for them to occur that goes up the higher above 100% it is.
- Should this option be used if meltdowns are disabled or have to be enabled in addition? My instinct tells me that if meltdowns are disabled it probably should just be used instead.

The bigger issue though which may end up being a blocker from this ending up in 10.1 is that I am unsure if the reactor will just be able to be started backup via redstone (or CC integration for that matter). Though that can probably be at least partially solved by making it so the reactor can't be turned on when it is above the percentage (though if that is past 100% it might be weird it can start again before reaching 100%). 

Would it make more sense to instead have the config option for if meltdowns are enabled or not be changed that if the chance is hit that it would meltdown then if they are disabled it just turns off the reactor and won't let it be started again until it is below 100% damage?

**Comment by stevenhay** [comment]
> Should I cap such a config option at 100% or higher? Given how meltdowns currently work is that there is a percentage chance for them to occur that goes up the higher above 100% it is.

If meltdowns are disabled I think a hard cap at 100% would be the best solution here. After all, with meltdowns enabled, you're running a chance at a meltdown at 100% anyway, even if the chance is quite small.

> Should this option be used if meltdowns are disabled or have to be enabled in addition? My instinct tells me that if meltdowns are disabled it probably should just be used instead.

I think that it should be the default behaviour should meltdowns be disabled, I'm not seeing a good use case (outside of potential strange, niche testing worlds?) for allowing a reactor to continue generating power - or even be active - after it's reached 100% damage. It could also work if meltdowns are enabled but I'm a little worried about it causing an issue with the meltdown chance if it auto turns off at 100% damage.

>Would it make more sense to instead have the config option for if meltdowns are enabled or not be changed that if the chance is hit that it would meltdown then if they are disabled it just turns off the reactor and won't let it be started again until it is below 100% damage?

This could also work, yeah. I was thinking along the same lines, once it reaches 100% damage it can't be turned on again until going under 100%, or even lower if you'd like to balance it around meltdowns. If the meltdown chance is hit then the reactor can't be started again until it reaches 0% damage (maybe only for when meltdowns are disabled?), then it's slightly punishing in terms of wait time, but not as much as having to rebuild when meltdowns are active.
