### ISSUE TITLE
Option to disable Machines in config [1.16.5]

### ISSUE THREAD

**Issue by I3estOFF** [mekanism/Mekanism-Feature-Requests#318]
### Describe the feature you'd like

Like in older versions, option in config to disable e.g. Digital Miner from game

**Comment by pupnewfster** [comment]
Just remove the recipe and if you want hide it from JEI.

**Comment by I3estOFF** [comment]
I have to remove recipe in mod file?
just delete Digitalminer json file?

**Comment by SirEndii** [comment]
With Crafttweaker or kubejs
Never edit a .jar by yourself

**Comment by pupnewfster** [comment]
Either use a datapack (a vanilla system), or as seniorendi said you can use CraftTweaker or KubeJS to remove recipes.
