### ISSUE TITLE
Wireless Power Transfer

### ISSUE THREAD

**Issue by Luingar** [mekanism/Mekanism-Feature-Requests#328]
### Describe the feature you'd like

QIO brings wireless items transfer to the game with the portable QIO dashboard. With that in mine, i propose there also be a way to transfer power wirelessly in a similar way. Probably the simplest way would be to tap into the same thing, using a QIO Energy importers and exporters, as well as  a QIO energy tablet. possibly also an array of QIO energy drives, but i think those would be unnecessary, and instead the player should be encouraged to simply add importers and exporters to their induction matrices

### Describe alternatives you've considered

Wireless energy tablets you pair together, one input and one output, or power storage blocks like energy cubes that link together and share power levels with other cubes with the same frequency, syncing each time the chunk containing them loads or they're accessed.

**Comment by pupnewfster** [comment]
Can't this just be done with Quantum Entangloporters? Not to mention QIO Energy makes zero sense as the `I` in `QIO` literally stands for `Item` and Energy is not an item.

**Comment by Luingar** [comment]
> Can't this just be done with Quantum Entangloporters? 

yes.
