### ISSUE TITLE
Extended vein mining

### ISSUE THREAD

**Issue by TheSilentD3ath** [mekanism/Mekanism-Feature-Requests#335]
### Describe the feature you'd like

Since you removed extended vein mining on the Atomic disambler to encourage switching to the meka tool. Maybe it would be fair that the extended vein mining on the meka tool becomes as effektiv, as it was with the atomic disambler. 

### Describe alternatives you've considered

Just give the feature back for the atomic disambler but make it optional to have be possible to use.

### Additional context

Because trying to terraform big places takes for ever like that, with the meka tool. so your stuck using worldedit (which isn't really survival friendly if cheating is not an option for you) or the older version 10.0.24.453. I mean you could also use explosives but that isn't really safe, if you are using the feature for building in your base.

**Comment by NullPointerCollection** [comment]
Have you gone into the module tweaker to increase the excavation range?

![image](https://user-images.githubusercontent.com/59610016/148135735-d059146e-6152-462c-883e-b29f608ae847.png)

**Comment by TheSilentD3ath** [comment]
> Have you gone into the module tweaker to increase the excavation range?
> 
> ![image](https://user-images.githubusercontent.com/59610016/148135735-d059146e-6152-462c-883e-b29f608ae847.png)

Yes but when I look into it the excavation range it only goes up to 2? 
I have the version 10.1.1.456 installed.

**Comment by NullPointerCollection** [comment]
Do you have only 1 vein mining unit installed?  You need 4 to get to the range of 8.  You can see in my screenshot that 4 are installed.

**Comment by TheSilentD3ath** [comment]
> Do you have only 1 vein mining unit installed? You need 4 to get to the range of 8. You can see in my screenshot that 4 are installed.

Well now it works, I never used it. So I didn't know that ^^'
But thank you ^-^ 

I have more than enough nuclear waste left in my survival server so making more upgrades for me and my friends shouldn't be an issue..
