### ISSUE TITLE
Being able to craft creative stuff

### ISSUE THREAD

**Issue by karpot35** [mekanism/Mekanism-Feature-Requests#343]
### Describe the feature you'd like

I think being able to craft creative energy cubes, creative fluid tanks and stuff like that would be nice but it should be so hard to make for example using thousands of antimatter a lot of energy or stuff like that.

### Additional context

Being able to craft creative stuff but making it hard to not be that op.

**Comment by ghost** [comment]
You can add recipes for things by yourself with things like datapacks, kubejs, or crafttweaker.

**Comment by pupnewfster** [comment]
No there is a reason it is creative. If a pack dev wants to add recipes for them that is their choice, but we will not be doing so.

**Comment by karpot35** [comment]
ok thank you
