### ISSUE TITLE
Add Modrinth download

### ISSUE THREAD

**Issue by enderger** [mekanism/Mekanism-Feature-Requests#348]
### Describe the feature you'd like

Modrinth is an open source platform for hosting Minecraft mods, and with coming CurseForge changes which hamper support for third-party launchers it might be wise to have another mirror. It also provides a Maven (which could probably be used as a mirror) and is working on modpacks and monetisation.

### Describe alternatives you've considered

Remaining CurseForge/website only, though that would not have much gain given site download already being a way to download it sans CF and the marginal benefits from their reward system.

### Additional context

https://modrinth.com
https://github.com/modrinth/minotaur (Gradle plugin)

**Comment by asdf3601a** [comment]
Maybe also setup CI to make release on Github?

**Comment by pupnewfster** [comment]
First step of this has been done: https://twitter.com/pupnewfster/status/1530043960709853184
Second step that I will start looking at tomorrow is making use of that gradle plugin.

In regards to releasing on GitHub I see no reason or benefit in doing so, especially as we publish to a maven.
