### ISSUE TITLE
Mekanism MC1.12.2 - Laser Amplifier

### ISSUE THREAD

**Issue by SorinMarkov01** [mekanism/Mekanism-Feature-Requests#353]
### Describe the feature you'd like

I would like to be able to change amount of energy stored in Laser Amplifier. In config file there is Laser config but Laser Amplifiers config cannot be changed. Laser Amplifier has max storage set default to 2.0GRF and this can't be changed in config files.

example:
                  # Base energy storage (Joules).
                  D:LaserStorage=2000000.0

                  # Base energy storage (Joules).
                  D:LaserAmplifierStorage=15000000.0

**Comment by pupnewfster** [comment]
This is not going to happen for 1.12 as we are no longer developing for it, but this does seem like a very reasonable request and something I will look into for the 1.18 release.

**Comment by SorinMarkov01** [comment]
Thank you for your quick reply. I'm glad, that I could help, even a little. I'm still playing on version 1.12.2, but when all of my favourite mods get 1.18 update, I would be happy to enjoy this feature. :)

**Comment by SirEndii** [comment]
No reason to close this because this is now a issue/request for 1.18
