### ISSUE TITLE
Die in Reactors.

### ISSUE THREAD

**Issue by Richard5A** [mekanism/Mekanism-Feature-Requests#357]
### Describe the feature you'd like

I was in a Fission Reactor and it was on and thought why don't I drown or get damaged by the fission.
My idea is to make (if it's water cooled) make you as you where underwater and you'll get damage from the heat of the fission.
The same with other reactors

**Comment by pupnewfster** [comment]
This already happens. Fission irradiates entities inside and fusion does "magic" damage.
