### ISSUE TITLE
customizable Mekasuits

### ISSUE THREAD

**Issue by Kazutwo** [mekanism/Mekanism-Feature-Requests#360]
### Describe the feature you'd like

having a feature where you can customize the colour of the Mekasuit, possible having it so you can change it from the modification station. the Meka suit is very cool, but i think having the ability to personalize would make it a lot cooler, especially if you and your friends all have Mekasuits

**Comment by NullPointerCollection** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/72

A year and a half old with a few duplicates. Please close this.
