### ISSUE TITLE
Autocrafting

### ISSUE THREAD

**Issue by BraveCaperCat** [mekanism/Mekanism-Feature-Requests#361]
### Describe the feature you'd like

Machine, that automatically crafts, like a crafting table, i would also like mod support!

**Comment by toddlersizedsharkcage** [comment]
Other than the formulaic assemblicator or QIO crafting grid?

**Comment by a1qs** [comment]
thats what a formularic assemblicator does

**Comment by BraveCaperCat** [comment]
> Other than the formulaic assemblicator or QIO crafting grid?

Oops i didn't know, that there was already a autocrafter already, Just no called "Autocrafter"
