### ISSUE TITLE
Refined Storage/AE2 Support

### ISSUE THREAD

**Issue by BraveCaperCat** [mekanism/Mekanism-Feature-Requests#362]
### Describe the feature you'd like

Anywhere a logistical transporter, can connect to any machine, so should a storage system

### Describe alternatives you've considered

Issue, not a feature request

### Additional context

Could be an issue if invalid,
can always be "Fixed", by placing logistical transporters so it goes into a chest, that can then be imported from!
The "Issue" can be solved by making transporter connections, a "Storage"

**Comment by pupnewfster** [comment]
Copied from our FAQ on discord:

**Q:** *Is there a way to connect the QIO to Refined Storage or Applied Energistics 2?*
**A:** Currently no, we do not expose the QIO's inventory as an IItemHandler as not only would it be a headache to wrap into an IItemHandler it would be little more than a lag switch for players as "external storage" systems using IItemHandlers that RS/AE2 have native compat with scale really poorly with the more types of items there are. Mekanism's QIO was designed to be able to store mass amounts of items without causing lag. If someone wants to go ahead and implement the proper solution and make a compat addon between our QIO and either RS and/or AE2 that teaches the other system(s) how to read our advanced item cache, we are willing to help explain how our system works and move various parts of it to our API.

(And I believe for the most part other than at the end of logistical sorters the importers/exporters can be placed anywhere the logistical transporters currently can be)

**Comment by BraveCaperCat** [comment]
I don't use discord!
