### ISSUE TITLE
Dump energy

### ISSUE THREAD

**Issue by Appdato** [mekanism/Mekanism-Feature-Requests#377]
### Describe the feature you'd like

I would like to have the option of dumping energy inside energy cubes and an induction matrix. This will allow the non-stop of the turbine. the stopping of the turbine when its energy is full stops the water output, which in a fission reactor setup would be fatal.

### Describe alternatives you've considered

Allow the turbine to work even if his power is full, maybe with a toggle of his old functionality and its new feature.

**Comment by beholderface** [comment]
Resistive heaters can have their energy consumption set extremely high. Comparators can be used to measure the charge of induction matrices. Energy cables can be redstone controlled. You can use these features to set up a system which allows energy out of the matrix into a heater (or several) when it is close to filling up, essentially functioning as a dump excess system.

**Comment by pupnewfster** [comment]
No, you can use a comparator to stop a fission reactor when your energy storage is full.
