### ISSUE TITLE
Mekanisim and Inventory HUD+ 

### ISSUE THREAD

**Issue by CuriousGamer2** [mekanism/Mekanism-Feature-Requests#380]
### Describe the feature you'd like

I noticed that whenever I'm using Inventory HUD+ weapons in the Meninism mod doesn't display the durability which would be a percentage.

**Comment by pupnewfster** [comment]
I am not quite sure what this request is requesting... Especially given it doesn't look like inventory hud+ is open source nor has an API. And if they don't show durability of our stuff that just sounds like a bug on their end if they are supposed to?

**Comment by CuriousGamer2** [comment]
> I am not quite sure what this request is requesting... Especially given it doesn't look like inventory hud+ is open source nor has an API. And if they don't show durability of our stuff that just sounds like a bug on their end if they are supposed to?

It does show the durability [Checked it again] just not what other modded tools and weapons durability would look while using the mod which would be just a percentage.
