### ISSUE TITLE
1.18.1 please

### ISSUE THREAD

**Issue by Shapaper** [mekanism/Mekanism-Feature-Requests#381]
### Describe the feature you'd like

1.18.1 please

### Describe alternatives you've considered

1.18.1 please

### Additional context

1.18.1 please

**Comment by NullPointerCollection** [comment]
This is not happening

**Comment by pupnewfster** [comment]
Respect please
Respect please
Respect please
Respect please

**Comment by Shapaper** [comment]
> 请 尊重 请 尊重 请尊重 请 尊重

I mean no harm

**Comment by pupnewfster** [comment]
If you want it that badly you can compile it from old commits.
