### ISSUE TITLE
Suggestion: Elytra Unit shouldn't take antimatter to craft

### ISSUE THREAD

**Issue by WFPhantom** [mekanism/Mekanism-Feature-Requests#383]
### Describe the feature you'd like

First off, yes i know i can change the recipes with KubeJS/CraftTweaker/Datapacks but I like to play with default recipes and this is only a suggestion.

The Elytra Unit Shouldn't take Antimatter to craft, for the price of just two more antimatter you could craft the gravitational modulating unit which basically renders the elytra/jetpack unit useless. The Elytra unit could take like 7 polonium to craft to make it more balanced but I don't see myself using antimatter for it.

**Comment by pupnewfster** [comment]
We currently have no plans to change the recipe, especially with how strong the elytra is when paired with the jetpack unit or fireworks. Also elytra's provide a lot more horizontal momentum than the creative flight of the gravitational modulating unit.
