### ISSUE TITLE
A different energy system

### ISSUE THREAD

**Issue by Basgamer999** [mekanism/Mekanism-Feature-Requests#385]
### Describe the feature you'd like

This is a stupid brainwave from me so maybe its not even possible or cause alot of lag. My idea was to have a new energy system system with voltages, ampere and watt. Some machines require more voltage or watt. the ampere is for how much power you generate so how much things you can connect at ones without running out of energy. This will require a new block that can convert low voltage to high voltage (with a small lose because thats realistic) and machines don't function on too low voltage but break when they get connected to too high voltage. 

### Describe alternatives you've considered

The current system is already pretty good this was just a suggestion for a more realistic system

### Additional context

If you want that i respond faster ping me on discord Basgamer999#9392 i dont check github that often.

**Comment by beholderface** [comment]
this just sounds like IC2

**Comment by RotatingBuffalo** [comment]
This would remove the "universal" from the universal cables. I'd rather just keep things as they are.

**Comment by pupnewfster** [comment]
This doesn't seem like it would really fit mekanism's way of doing things
