### ISSUE TITLE
Change the oregen settings to global instead of per world.

### ISSUE THREAD

**Issue by Sakatsuky** [mekanism/Mekanism-Feature-Requests#398]
### Describe the feature you'd like

I believe that it would be better to disable the oregen globally instead of per world, so ores os mekanism would not generete on the spawn chunks, that would make it more practical to set up a mod like AllTheOres, so no overlap of ores would happen.

**Comment by Matyrobbrt** [comment]
This is what defaultconfigs are for

**Comment by pupnewfster** [comment]
I am confused... all our configs are global?
