### ISSUE TITLE
Ore refinement unit with configurable amout of max upgrades

### ISSUE THREAD

**Issue by edotenseilove** [mekanism/Mekanism-Feature-Requests#399]
### Describe the feature you'd like

I like the new ore refinment unit but I think that the amout of possible upgrades should be configurable because for example in some modpacks there are ways of obtaining higher levels of fortune (apotheosis, quark) and if that is the case than the amout of upgrades is not sufficient and it would always be better to go with regular enchanted pickaxe or silk touch module.

**Comment by pupnewfster** [comment]
No.
- I don't really like the idea of configs change stack sizes of things
- We don't have to be the "best" option for everything 
- And the biggest reason... The module may not even survive long term for reasons mentioned here https://github.com/mekanism/Mekanism/pull/7467
