### ISSUE TITLE
Make the mekasuit immune to true damage from mods like Botania

### ISSUE THREAD

**Issue by R4ng3x** [mekanism/Mekanism-Feature-Requests#401]
### Describe the feature you'd like

It would be nice if the mekasuit was able to somehow curb the true damage that some mods add to minecraft, which makes it incredibly easy to kill someone with a mekasuit

**Comment by pupnewfster** [comment]
No, we respect mod compat.. If they mark their damage as bypassing armor, then we will let it bypass it. If an addon wants to add a module that blocks additional types of damage that including ones that bypass armor, it should be relatively straightforward.
