### ISSUE TITLE
Add recipe for `Cobweb -> String` using the Enrichment Chamber

### ISSUE THREAD

**Issue by alyxandraio** [mekanism/Mekanism-Feature-Requests#402]
### Describe the feature you'd like

Title is pretty self-explanatory. I think it would be a nice addition to be able to enrich cobwebs into string.

### Additional context

I'm mining cobwebs with the Digital Miner for string, and it's a bit tedious to have to break them myself.

**Comment by alyxferrari** [comment]
Nevermind, I'm working on adding it myself. Give me a bit.
