### ISSUE TITLE
Allow to copy-paste a machine's config with the configurator

### ISSUE THREAD

**Issue by JonasDoe** [mekanism/Mekanism-Feature-Requests#419]
### Describe the feature you'd like

It would be nice if the configurator had an option to copy-paste the io config from one machine to another one (including auto-inject), because it's rather messy and error prone to get it right in a plant right now. The only downside would be that ppl. might be encouraged to skip speed upgrades and in favor of multiple machines, and that might not be what you wanted.

### Describe alternatives you've considered

For a bigger rework and new machinery, machines could work with configuration cards you can insert, and there would be "workbench" block to allow to store/load config and write them into machines. Different tiers for the workbench could allow more config storage or more configuration options (which would be a nice progression but is not really coherent with how tiers work at the moment.)
But yeah, that would mean quite some work and might not adhere to the vision of Mekanism you have.

**Comment by beholderface** [comment]
Configuration card. Already exists.

**Comment by JonasDoe** [comment]
Wait, what? My life was a lie! :D
Thanks!
