### ISSUE TITLE
Armored Free Runners feature request

### ISSUE THREAD

**Issue by Snorlax1337** [mekanism/Mekanism-Feature-Requests#425]
### Describe the feature you'd like

I would like to have an option to turn off the automatic Step Assist on the Armored Free Runners.
While its a nice thing to have in general, i would like to be able to turn if off in specific situations.
It makes placing blocks and surviving around my terrible wiring in a modpack really frustrating at times.

I love your mod and thank you for reading my request. 

### Describe alternatives you've considered

Dying without them. Often.

### Additional context

Im fairly new to modded minecraft, so while my "problem" is rather a skill issue, i would still like the freedom of choice.

**Comment by Omikron-Delta** [comment]
You can disable auto step assist by using the Feet Mode Switch button (whatever it's configured to in your key binds, B by default)
