### ISSUE TITLE
Add a config option for how much U-235 a fission reactor burns

### ISSUE THREAD

**Issue by Evrey** [mekanism/Mekanism-Feature-Requests#427]
### Describe the feature you'd like

While super fun and powerful, a fission reactor in Mekanism just eats through unreasonable amounts of uranium. A real large power plant consumes something like 120 tons of Uranium a year. That’s just a single truck full of rods.

The proposed solution is to add config options for uranium consumption, possibly also for fusion reactor and gas burner fuel consumption while at it. Create default settings that match the *current* balancing. But people like me can then turn their consumption way down.

### Describe alternatives you've considered

As an alternative i currently feed my fissile fuel production with creative mode infinite uranium ore barrels. Not as fun, but works.

### Additional context

I’m not racing towards ever more powerful reactors. The fission reactor looks great, and i use just that for power generation.

**Comment by AlexHgC** [comment]
More fission rate = more consumption 
Less fission rate = less consumption

Actual config are fine imo, maybe you play on a modpack with modified config ? 
Take in mind that fission isn't the best for energy production, it's mostly used for Polonium.
For energy, build a fusion, infinite energy without any ores

**Comment by pupnewfster** [comment]
Can't you just change the recipe for fissile fuel using datapacks, CraftTweaker, or KubeJS so that it requires less uranium to create each mb of fissile fuel? That is effectively the config you are asking for.

**Comment by Evrey** [comment]
@pupnewfster Hmm, that’s a good idea i somehow didn’t think of, thanks.
