### ISSUE TITLE
Portable Electrolysis Unit

### ISSUE THREAD

**Issue by scarabx** [mekanism/Mekanism-Feature-Requests#430]
### Describe the feature you'd like

A portable electrolysis unit, that you can wear, that needs to be powered and that produces oxygen and hydrogen and pumps it into your hydrogen and oxygen using tools, e.g. jetpack, flamethrower, scuba tank, etc. 

### Additional context

It is a real pain to check my fuel gauge all the time, and to have to refill my tools after such a short time. Therefore it would help a lot to be able to refill on the fly.

**Comment by UnknownSerhan** [comment]
You know there is a module for that for MekaSuit, where you can breathe underwater and fill your jetpack and other things that accepts hydrogen.

**Comment by pupnewfster** [comment]
As mentioned this is already a thing

**Comment by scarabx** [comment]
Oh, sorry. My bad. Thanks a lot for telling me.
