### ISSUE TITLE
Atomic disassembler vein mining

### ISSUE THREAD

**Issue by scarabx** [mekanism/Mekanism-Feature-Requests#433]
### Describe the feature you'd like

Will you please add the vein mining and extended vein mining back to the atomic disassembler. That's why I like the atomic disassembler, without this feature it's useless to me.

### Describe alternatives you've considered

 Or at least please add a config option to enable it or at least add only vein mining to disassembler.

**Comment by Omikron-Delta** [comment]
This was removed from the Atomic Disassembler in favor of adding it to the Meka Tool.

**Comment by pupnewfster** [comment]
There is a config option to re-enable normal vein mining

**Comment by scarabx** [comment]
Does it enable it for the dissasembler?

**Comment by pupnewfster** [comment]
Yes... why would I mention a config option for something else when we are talking about the disassembler?

**Comment by scarabx** [comment]
I thought you meant it changes the mekatool to only have normal vein mining. Thank you very much for adding a config to mekanism for enabling vein mining for atomic dissasembler.
