### ISSUE TITLE
Add inventory protection to Robits?

### ISSUE THREAD

**Issue by NovaLynxie** [mekanism/Mekanism-Feature-Requests#435]
### Describe the feature you'd like

Hi there. I would like to request if Robits can be given security protection OR have the upgrades to do so.
Mainly because the following item used in crafting a Robit has this feature but as far as I can tell is not applied to Robits themselves.
![image](https://user-images.githubusercontent.com/21307676/185847793-5aa72371-ccb9-497b-acc9-ee3bfad816a5.png)
Robit recipe (from 1.12.2 version, assuming its the same going forward)
![image](https://user-images.githubusercontent.com/21307676/185847829-6a30ac97-ee8f-4524-a4b4-a6c26a8eeaa0.png)

### Describe alternatives you've considered

None available, would normally keep secured in claimed areas but these require additional mods to do this or I'd just stow the Robit safely away in any inventory.

### Additional context

Say for example you are going mining and you want to store items on the go on a multiplayer world. You may find some others who do not respect your privacy and will take items without asking.

Having this feature will prevent anyone from getting access much like a personal chest being placed and have the same security features so that only those you trust in a security station will be allowed access to use your Robit's utilities and portable storage options.

I have looked for any existing requests and found none that match this.

**Comment by pupnewfster** [comment]
What version are you on given I am fairly certain sometime during 1.16 I made it so you can change the security mode of robits.

**Comment by NovaLynxie** [comment]
1.12.2 9.8.3.0.390 was the version I used. Idk if any new features are gonna be added ofc.
Good to know that it may be in newer versions, I'll have to check though since I haven't used robits since 1.12.2

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism/commit/b1b8e30790fb3af9cd6aaa77d0724a68d95c515a

**Comment by NovaLynxie** [comment]
Just checked and that does exist on newer versions. Am assuming not gonna be added to older ones.
Good to know though it was added at least 👍🏼
