### ISSUE TITLE
Add option in config to increase explosion area

### ISSUE THREAD

**Issue by fa5tkill3r** [mekanism/Mekanism-Feature-Requests#438]
### Describe the feature you'd like

In Mekanism configs add option which represents multiplayer or something like that which will affect reactor explosion area because i just feel like current value is little bit too low. Altho it may be okay for someone so i think config property would be great enhancement.

**Comment by pupnewfster** [comment]
I think this should be pretty straightforward to do for 10.3.3, BUT due to where things are odds are the config would end up in the main mekanism config rather than one of the mekanism generators configs.

**Comment by pupnewfster** [comment]
Actually scratch that with a couple tweaks odds are I can make it in the generators config with the rest of the fission stuff.
