### ISSUE TITLE
Armor Infusion

### ISSUE THREAD

**Issue by TheDoc989** [mekanism/Mekanism-Feature-Requests#464]
### Describe the feature you'd like

In Fiskfille's Transformer Mod (1.7.10), there is a feature where you could "insert" armor into the transformer suits. I was wondering if this feature could be implemented with the Mekasuit? The inserted armor basically covering the entirety of protection, for example if I were to insert the Infinity armor from Avaritia, or the Gem Set from ProjectE, I wouldn't take damage, while still having the benefits of the Mekasuit.

![Screenshot (68)](https://user-images.githubusercontent.com/50060468/194157706-caf7e489-79de-4996-adea-ce658a57e83c.png)

### Describe alternatives you've considered

 Either the way I mentioned above, or maybe something simpler, like adding the protection value to the Mekasuit like in the image.

### Additional context

I basically thought of this because of a recent encounter with a Warden, the Gem set could easily tank its sonar beam attack while the Mekasuit couldn't. Although the mekasuit suit did easily take its physical hits.

Just a completely random idea I had

**Comment by pupnewfster** [comment]
Personally I don't think this really fits the goal of the meka suit, nor does it sound like something that would be particularly easy to implement. Also I am not positive but I would not be surprised if the inhalation purification unit which helps protect against "magic" damage would provide some protection against the warden.
