### ISSUE TITLE
Clear QIO Crafting Window to System 

### ISSUE THREAD

**Issue by Legoman9571** [mekanism/Mekanism-Feature-Requests#468]
### Describe the feature you'd like

Whenever you craft something (for example a redstone torch) and then craft something else (a door for example) in the same crafting window in a QIO system, the excess items from the previous craft (sticks and redstone) are put into your inventory. I think it would make more sense if the items went straight back into the system similar to AE2's system. 

### Describe alternatives you've considered

I know you can move individual items by just using the mouse, but as someone who uses shift-clicking and other new features added by Inventory Tweaker religiously, it would make the whole experience a lot smoother.

### Additional context

This is more of a QoL request than anything, but it saves the time of taking the items out of the crafting window, putting them into your inventory, and closing the window (otherwise the items will be put back into the window if shift-clicking), and finally putting them back into the system.

**Comment by pupnewfster** [comment]
Just click the button to clear the grid to the QIO that got added a while back?

**Comment by Legoman9571** [comment]
![asd](https://user-images.githubusercontent.com/113043398/195456101-be28db94-7340-4c6d-bd46-6e0427cb5693.png)

What button? If you're referring to the X it still saves what was in it.

**Comment by pupnewfster** [comment]
https://user-images.githubusercontent.com/1203288/195628825-33d34773-9db1-49c4-a239-8e41fe99aac2.mp4

This one that got added in 10.3.1

**Comment by Legoman9571** [comment]
> java_rdyTiqukfA.mp4 
> 
> This one that got added in 10.3.1

Oh what the heck. I don’t have that button for some reason (above screenshot). I’m using the latest version for 1.18.2 if that makes a difference. Or at least I thought I was it says version 1.18.2-10.2.5.465.jar. I wonder why CurseForge didn’t tell me it needed updating. Sorry about all this. Thank you for the help and your amazing work on this mod!

**Comment by pupnewfster** [comment]
That would be because this was part of one of the updates to 1.19 (which is the only version we are currently developing for)

**Comment by Legoman9571** [comment]
Are there any plans to update previous versions?

**Comment by pupnewfster** [comment]
No

**Comment by Legoman9571** [comment]
Fair enough, thank you for the help! And thank you again for all the hard
work :)
