### ISSUE TITLE
Gaze Obfuscation Unit

### ISSUE THREAD

**Issue by beholderface** [mekanism/Mekanism-Feature-Requests#470]
### Describe the feature you'd like

This would be a Mekasuit module that makes it so that your gaze does not anger endermen. Goes on the helmet, the more you install, the closer you have to be in order to aggro an enderman, up to no gaze aggro at all with 4 units.

### Describe alternatives you've considered

IDK, maybe a standalone helmet item that gives you Mekasuit-like HUD elements and includes the effects of this and the Vision Enhancement Unit. Could be used in the crafting recipe for gaze obfuscation unit if they were both added.

### Additional context

¯\\\_(ツ)\_/¯

**Comment by pupnewfster** [comment]
The meka suit helmet already makes it so looking at endermen don't get angry by default. Is the idea of this feature request just to remove that and instead have a unit that controls it?

**Comment by beholderface** [comment]
I was not aware of that, I don't often look at endermen in the first place.
