### ISSUE TITLE
Cubical Tank multiblock

### ISSUE THREAD

**Issue by koalalord9999** [mekanism/Mekanism-Feature-Requests#484]
### Describe the feature you'd like

It would be cool if we could get a Railcraft style tank multiblock using the existing tanks, or a new one that maybe holds less MB per block, and becomes connected (textures and all). While still maintaining the upward input and the bottom output.

**Comment by DripThanos** [comment]
have you ever heard of Dynamic Tank multiblocks?

they are really cheap and can store a crap ton of 1 fluid.

using valves you can make it input or output on any side that has a valve, and you can have as many valves as you want so long as they aren't on a corner of a face
also you can replace most of the dynamic tank(s) ~~casings~~ with structural glass

**Comment by koalalord9999** [comment]
Oh.. nope, never even seen it. My bad, will close, as waste of a slot
