### ISSUE TITLE
Qio autocrafting

### ISSUE THREAD

**Issue by SharkBairRFSR** [mekanism/Mekanism-Feature-Requests#487]
### Describe the feature you'd like

an auto crafting feature in QIO sort of like applied energistics,
A crafting pater made with 8 crafting patterns and a polonium pelet to make a qio crafting patern
a crafter made like the qio drive but middle block is an auto crafter
each qio patter allows for 9 recipes
in the qio you can see hat you can craft and que them up (crafter requireds power)
and it will use its contents to make items

### Additional context

this would be an alternative for the recursive crafting of energy cubes where you can quee it up and wait for it to craft from base elements
it also expands on the qio idea in mekanism
will also tell you what items are needed for the recursive crafts and what items may be missing

**Comment by pupnewfster** [comment]
There is no plan for on demand auto crafting. Stock keeping based auto crafting already exists though eventually might get further QoL improvements like #476

**Comment by SharkBairRFSR** [comment]
Alright well how about an item like the dictionary that tells you how many of the base items are needed for crafting
