### ISSUE TITLE
Add subcommand to `mek radiation` to add radiation to a player or entity

### ISSUE THREAD

**Issue by James103** [mekanism/Mekanism-Feature-Requests#488]
### Describe the feature you'd like

There should be a subcommand in `mek radiation` to irradiate any player or entity with a given amount of radiation.
This could be useful for command-based data packs which currently need to rely on `data merge/modify entity` and/or `execute store result entity`, both of which do not work on players.

Possible syntax:
`mek radiation irradiate <magnitude> [<entity>]` (`entity` defaults to `@s` if not specified)
Alternative:
`mek radiation irradiate <entity> <magnitude>`

(the name `irradiate` is subject to change)

### Describe alternatives you've considered

`data merge/modify entity` can set an entity's radiation level to a specific value, but does not work on players.
`execute store result entity` can set an entity's radiation level based on the result of a `scoreboard players get` command or another command, which is useful for having custom radiation. Again, this does not work on players.

It may be possible to use `mek radiation add` to inflict the radiation, but that command inflicts radiation in an area (possibly affecting many entities), not to a specific player or entity.

**Comment by pupnewfster** [comment]
Should be simple enough, will try to add it into 10.3.6 when I get around to working on it. Would you expect a command like this to support negatives (and auto clamp at baseline) or only allow irradiating entities with it given `/mek radiation heal` can be used to reset an entity's radiation to baseline. For reference I don't believe `/mek radiation add` supports negatives so I would be inclined to make this command not do so, but I could see a desire for a way to decrease it by a specific amount or also have one to query an entity's radiation level (I forget if that already exists). But let me know if you want any of those other sub commands (I don't actually tend to work with commands much from a datapack perspective so I am not sure if querying radiation of a player would even be useful as I don't know if you can utilize that result).

**Comment by James103** [comment]
The command to query an entity's radiation level in microsieverts would be as follows:
```
data get entity @s ForgeCaps.mekanism:radiation.radiation 1000000
```
Change the last number (`1000000`) to 1 or 1000 to get the result in sieverts or millisieverts respectively.

The new subcommand does not need to support reducing an entity's radiation level (though it would be nice); it can already be done by querying the radiation into a scoreboard objective, changing it with scoreboard operations, then either storing the new value directly or using `mek radiation heal` followed by the new subcommand to set the radiation.

**Comment by pupnewfster** [comment]
I probably will make it support reducing or add a separate sub command for reducing. And good to know there is already a way to query the radiation value.

**Comment by pupnewfster** [comment]
Whenever 10.3.6 is released it will contain two new sub commands to modify an entity's radiation:
```
/mek radiation addEntity <magnitude>
/mek radiation addEntity <targets> <magnitude>

/mek radiation reduce <magnitude>
/mek radiation reduce <targets> <magnitude>
```
