### ISSUE TITLE
Hydrofluoric acid doesn't damage skeletons

### ISSUE THREAD

**Issue by Phalcone42** [mekanism/Mekanism-Feature-Requests#489]
### Describe the feature you'd like

This is an outrage! I've created a setup to automate the production of oceans of hydrofluoric acid, but for some reason it isn't giving my character a heart attack when I jump into it. It also seems to not damage skeletons, despite being composed of bones. Please fix this issue, it is a critically impacting bug. 

### Describe alternatives you've considered

I will accept no alternative to hydrofluoric acid causing damage. 

### Additional context

https://en.wikipedia.org/wiki/Calcium_gluconate
https://en.wikipedia.org/wiki/Hydrofluoric_acid

Shit eats bones.

**Comment by pupnewfster** [comment]
Merging into #59
