### ISSUE TITLE
Auto eject items toggle button should be easily accessed 

### ISSUE THREAD

**Issue by pwaksman973** [mekanism/Mekanism-Feature-Requests#490]
### Describe the feature you'd like

Although the auto eject items is accessible within 2 clicks, it would be much better if it was just below the auto-sort button.

### Additional context

it would make life so much easier at the beginning of the game, where you do want the machines close and working together but also want to do some stand alone recipes.

Sure multiple machines would suffice but, it is a very little early game suggestion that only affects quality of life, doesn't change anything that we already can do within the mod, just make it more accessible

**Comment by pupnewfster** [comment]
Not really feasible on the backend and I feel like it would be confusing to most users. If you want to setup a bunch of machines using the same settings you can always use a configuration card, and if it is just one having a single extra click isn't a big deal at all.
