### ISSUE TITLE
Disabling Configurator Chat Messages

### ISSUE THREAD

**Issue by 420Mora** [mekanism/Mekanism-Feature-Requests#495]
### Describe the feature you'd like

A client side option to disable the chat messages that come up when using the configurator. Accessible using Mod Menu or a similar mod. 

### Describe alternatives you've considered

Idk if thats already a thing or not. But to still show the Player what just changed, a small text above the hotbar that has the same/similar message that would normally be in chat.

**Comment by pupnewfster** [comment]
Wait, what version of MC are you on given I just did some misc testing and at least in 1.19 changing the mode of the configurator neither with the radial menu or by scrolling causes any messages appear.

**Comment by 420Mora** [comment]
Im playing in 1.16.5(OceanBlock FTB). But I meant when you change the side config of a machine or cable by clicking it with the configurator not just scrolling to change the mode of the configurator.

**Comment by pupnewfster** [comment]
Ah okay

**Comment by pupnewfster** [comment]
Sometime in 1.20.1 the majority of messages got moved to the status bar
