### ISSUE TITLE
Toggle-able elytra module for mekasuit

### ISSUE THREAD

**Issue by vaiium** [mekanism/Mekanism-Feature-Requests#497]
### Describe the feature you'd like

For the next iteration, can we get a hotkey toggle button equivalent to for example night vision?

Like press "button-x" to toggle the module on/off.

(Not the spacebar "toggle flight mode" that we already have, that toggles flight, not the module)

### Describe alternatives you've considered

So far unfortunately the only alternative i have is going into the mekasuit module menu, select elytra, select disable. Which is, well if you wanna switch from transport to building in a short time an annoyance to put it lightly. 

So the alternative i kind of got stuck on is not using the elytra module on the mekasuit. 

### Additional context

If you build and use a jetpack or the antigrav module. Sometimes you just need to double tap space to get the right angle. Everytime i do that, i start slowly floating down because of the elytra module which is a bother to the point i never use the elytra. 

If I could toggle the elytra module with a hotkey, i would start using it again. Travel=elytra building=jetpack/antigrav.

**Comment by pupnewfster** [comment]
Not sure of a good way to do this, so unsure when it will happen. In the meantime though you can press shift (or sneak, I forget which) to exit the MekaSuit's elytra glide instantly

**Comment by vaiium** [comment]
So, you have the toggle button for night vision module in the mekasuit settings menu: https://i.imgur.com/jQacM6B.png 
You have something similar for the elytra module: https://imgur.com/M5aCtzk
And if that could get a hotkey like this: https://imgur.com/baWSvSH
It would be perfect!

There is a chestmodule toggle hotkey already, but its not for the elytra.

**Comment by pupnewfster** [comment]
That is part of the issue, it might be able to work, but it may conflict with how the jetpack and grav unit use that keybinding already. (Though with there being an option to then choose which ones actually use the handle mode key, I suppose some of those toggles could just be disabled so as to not conflict if the elytra was added to supporting it). It definitely is something I plan on looking at, but it might be that for now it doesn't end up getting added to that if it behaves strangely

**Comment by vaiium** [comment]
In combination with iron jetpacks from "all the mods" pack something like that would be perfect. If it turns out to not work that would be unfortunate, but that you're willing to look at it is amazing already. Thanks for the responses!

**Comment by pupnewfster** [comment]
I think I will be implementing this for 10.3.6, with the sub details of:
- mode handling is disabled by default and needs to be enabled in the module tweaker
- it isn't possible to have the mode key for the jetpack or grav unit on at the same time as having the mode key for the elytra enabled
