### ISSUE TITLE
Custom gas support on 1.12.2

### ISSUE THREAD

**Issue by qchfor10000000100** [mekanism/Mekanism-Feature-Requests#498]
### Describe the feature you'd like

Im just wondering if you could get customed gas supproted on 1.12.2. You know more benefits eihter to the popularity and  better game experience for gamers are there. I do hope that it will receive a quick reply.
A more expected way to custom is with Crafttweaker or Contenttweaker.

### Describe alternatives you've considered

There's another means recommended that custom it with java. That might take a bit more easily to realize.

### Additional context

the following issue was written by a chinese gamer. if there were grammar mistakes in it, please contact me from the github!

**Comment by AlexHgC** [comment]
1.12 isn't supported anymore since a lot of time, and will not receive any updates. If you want custom gas, feel free to use higher version of Mekanism !

**Comment by UnknownSerhan** [comment]
Yeah currently any version below 1.19 is EOL (End of Life).

**Comment by pupnewfster** [comment]
Use the third party addon MekaTweaker
