### ISSUE TITLE
Fission Reactor meltdownsEnabled config option: backup

### ISSUE THREAD

**Issue by codefaux** [mekanism/Mekanism-Feature-Requests#502]
### Describe the feature you'd like

Hey! First and foremost, this is THE mod I kinda need any time I play. If Mekanism hasn't reached a Minecraft version, I'll wait for it.

To the point;

I'd love an option for the reactor to still meltdown, but to snapshot the area (or world/chunks/dimension/etc) somehow so that it can be un-done. I'm playing with the reactors, and I've got safeties set up, so they "should" work but I can't safely test that they -will-, lol.

Also, I'd actually like to -see- what happens if I do screw up, and live through the aftermath and whatnot for a bit, then roll back safely because it just ate most of my base and I know it's my fault but that's not fun. Yes, the config option to just shut off exists, but that's also less fun in a different way, right?

I know the server would grind to a halt during the save/backup period, but I think that's worth the sacrifice for those who would use it.

Anyway, consider it or not -- either way, thank you so much for your work.

### Describe alternatives you've considered

Really can't think of any safe way to do this, beyond intentional triggering meltdown after a manual backup, but that's less 'fun' entirely, right?

**Comment by SirEndii** [comment]
If you want to back up your reactor, just disable meltdowns
Or just one of the backup mods like FTB Backups

**Comment by pupnewfster** [comment]
Going to agree this feels a bit out of scope for Mekanism as there are plenty of mods to create backups of your world at desired intervals, and then you can always just do a partial restore of the chunks around your base.
