### ISSUE TITLE
Seismic Reader ComputerCraft Integration

### ISSUE THREAD

**Issue by saismeesaimonsaimes** [mekanism/Mekanism-Feature-Requests#507]
### Describe the feature you'd like

The ability for a ComputerCraft to read seismology information with an API.
The data could be obtained through a function such as "seismicreader.getColumn(x, y)," with the info returned as a table of strings, with each index corresponding to the Y co-ordinate.

**Comment by pupnewfster** [comment]
Sounds reasonable.

**Comment by pupnewfster** [comment]
Rough explanation of the methods added in 10.3.8 to the seismic vibrator:
isVibrating -> is it currently vibrating the chunk it is in
getBlockAt(chunkRelativeX, y, chunkRelativeZ) -> x and z are in the range of [0, 15] representing the position within the chunk the seismic vibrator is in, y is just the y value
getColumnAt(chunkRelativeX, chunkRelativeZ) -> same note as getBlockAt for the x and z
