### ISSUE TITLE
Increase x limit for digital miner!

### ISSUE THREAD

**Issue by thiagorodiani** [mekanism/Mekanism-Feature-Requests#524]
### Describe the feature you'd like

Currently, the digital miner limit is 64 on the x-axis.

Some dimensions like ATM Mining Dim go down to approximately -190.

It would be really cool to harness the power of the digital miner in these dimensions.

**Comment by pupnewfster** [comment]
Uhh presuming you mean on y, the digital miner's range scales depending on the ones declared by the dimension as bounds

**Comment by thiagorodiani** [comment]
Yes, sorry, i mean y-axis.

Nice to know, thanks for response

BR
