### ISSUE TITLE
Mod integration with tinker's construct

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mekanism/Mekanism-Feature-Requests#532]
### Describe the feature you'd like

Can you please add mod integration with tinker's construct 
For example 1 ingot of molten gold in tinker's means 200mb of molten gold in mekanism

**Comment by a-droid-boop** [comment]
Molten gold should fall under the forge library tag for molten ores. This is already implemented

**Comment by pupnewfster** [comment]
I am confused what you are asking because besides the fact we can transport tinker's molten gold via mechanical pipes and store it in tanks we don't do anything what so ever with molten gold?

**Comment by Ashwinaaaaaaahdt** [comment]
> I am confused what you are asking because besides the fact we can transport tinker's molten gold via mechanical pipes and store it in tanks we don't do anything what so ever with molten gold?

Sorry to confuse you 
In thinkers construct tank we can store 3 blocks of any metal
In mekanism ultimate tank it can store upto 4000 blocks of any metal as this tank can store upto 8192k mb of any fluid and 1 block of any metal is 1800 mb
So saving chest space is important
In 1 chest can store 1728 items so 3 chest are needed to store 4000 blocks of metal

**Comment by pupnewfster** [comment]
If the default configs aren't to your liking just change them `config/Mekanism/tiers.toml`
