### ISSUE TITLE
Storage chest upgrade 

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mekanism/Mekanism-Feature-Requests#545]
### Describe the feature you'd like

Regular storage can have upgrades like advanced storage, elite storage chest and ultimate storage chest.
An advanced storage chest would have 2x inventory space as a regular storage chest would have

An elite storage chest would have 2x inventory space as an advanced storage chest would have

An ultimate storage chest would have 2x inventory space as an elite storage chest would have
And also the ultimate storage chest would have a search bar like the qio drive
And all chests would show how much they can store like the qio drive

**Comment by pupnewfster** [comment]
Personally I don't see a point of this/don't feel like it fits Mekanism well. The entire point of the QIO is that it is a late game solution to item storage. The earlier game solution that Mekanism provides is bins. Adding searchable chests of varying massive sizes feels like it would intrude on the goal of the QIO

**Comment by Ashwinaaaaaaahdt** [comment]
> Personally I don't see a point of this/don't feel like it fits Mekanism well. The entire point of the QIO is that it is a late game solution to item storage. The earlier game solution that Mekanism provides is bins. Adding searchable chests of varying massive sizes feels like it would intrude on the goal of the QIO

But storage chest do act like shulker chest
