### ISSUE TITLE
Make freshly crafted machines stack and option to clear data by crafting

### ISSUE THREAD

**Issue by Twisted-Code** [mekanism/Mekanism-Feature-Requests#546]
### Describe the feature you'd like

So I just put enough materials into a crafting grid to craft 8 heat generators, before I realized I would need 8 inventory slots to carry them even though they were just crafted and have no important data yet. Can you please do something about that? It would also be nice to be able to reset the data by putting machines into the crafting grid by themselves, making them stackable again at the expense of whatever their data contained.

### Describe alternatives you've considered

If you can't make the item data start out "blank", can you at least make it so that items with the same NBT can stack?

### Additional context

If you need any clarification, feel free to at-mention me.

**Comment by pupnewfster** [comment]
I will try to think about this some more at some point as maybe it is time to re-address the decision, but at least historically the reason this has not been the case is that it gets very messy attempting to allow items to stack based on what data they have and can easily lead to dupes. Granted that was back in the days that Mekanism still used the same id for some different machines/tiers and just used NBT to represent the different types so making it that they can be stacked when they have *no* NBT might be something worth considering.

**Comment by Twisted-Code** [comment]
Yes, I think it might at least be feasible to make them stackable when they have no data. I think I see what you're saying about potential dupes, at least in theory, but can't think of a concrete example where that would happen. Do you have a concrete example in mind?

**Comment by Twisted-Code** [comment]
I should also note that them being stackable when new was like >90% of my request. If you can't make them stack when they have data, that's not as big a deal. I just want to be able to bulk craft them and place them. Like it's so tedious that I probably won't make anymore, I think wind generators make more energy anyway right? Not to mention this pack has both Bigger Reactors and your own playing-with-fire-or-rather-radiation fission reactors...

**Comment by Twisted-Code** [comment]
oh, don't forget my request to make it possible to reset their data so they can be stacked, once you have it so that blank data can be stacked. You know, kind of like EnderIO's crafting recipes when those were a thing? that's like the other 7% of my request other than the 3% that is "make items with data stack"

**Comment by Twisted-Code** [comment]
Thanks!
