### ISSUE TITLE
Protection upgrade for meka suit

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mekanism/Mekanism-Feature-Requests#548]
### Describe the feature you'd like

Protection upgrades would increase against any damage
The power of the Meka suit will decrease each time when you take a damage
Their protection level goes up till it reaches the same as refined obsidian armour level 4 protection
The Max stackability of the protection module will be 6

**Comment by pupnewfster** [comment]
The mekasuit already provides protection against all damage that isn't marked as bypassing armor.

**Comment by Ashwinaaaaaaahdt** [comment]
> The mekasuit already protects against all damage that isn't marked as bypassing armour.

What about the suggestion of labs and exp storage
