### ISSUE TITLE
Jetpack Glide Mode?

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism-Feature-Requests#55]
Basically it would be a fourth mode for the jetpack called glide

*regular
*hover
*glide
*disabled

This would work very similar to elytra except instead of using fireworks for propulsion, the jetpack's rocket would be used by pressing the space bar. This would allow for extremely fast travel over land with a penalty of using large amounts of hydrogen. Can only be used for short amount of times before needing to be recharged. it would be a fun addition that i believe would be easy to implement.

**Comment by ShibaRoTatsuya** [comment]
I would quite like this as elytra flight is the most enjoyable of the flight options. Though i think it should be separate from the jetpack mode switch as switching through 4 jetpack modes sounds like it would be a pain.

**Comment by codec-d** [comment]
I've seen comments about this for a few years now. Can we actually get it in? the jetpack is painfully slow

**Comment by ShibaRoTatsuya** [comment]
If you are using the mekasuit the jetpack is quite fast if you have locomotive boosts installed in the legs so speed isn't a worry. Elytra flight would just be fun.
