### ISSUE TITLE
Handle key customization

### ISSUE THREAD

**Issue by Minihercules317** [mekanism/Mekanism-Feature-Requests#563]
### Describe the feature you'd like

I would like to be able to choose what module my handle key affects on my meka items.

### Describe alternatives you've considered

The obvious alternative is just the options menu but I find this to be very tedious to have to deal with twice every single time you need to change a setting for 5 seconds to fix or do something.

### Additional context

I really don't need to change my meka tool efficiency often or at all but I do need to change whether vein mining is on or off quite often and this would make my life 10x easier. I find myself completely removing my boots rather than dealing with the system in place whenever I have to work in water and don't want everything around me turning into ice. This could be solved by at least choosing which module gets affected by the handle key. Of course, this is just a rough idea and could be refined very much but I would appreciate this very much as it helps improve the user experience greatly, thanks!

**Comment by pupnewfster** [comment]
Not going to happen due to how the system works, not to mention in the latest versions of mek the mode key can control both speed and vein mining
