### ISSUE TITLE
Multiblock Helper tool

### ISSUE THREAD

**Issue by Maykeye** [mekanism/Mekanism-Feature-Requests#564]
### Describe the feature you'd like

Right now figuring why multiblock doesn't want to build is an exercise in frustration: you put final casing and... nothing happens. Why? Who knows. The game has no mechanism to tell why. 

I propose a Multiblock Helper tool to help with it, which will work in three steps:

1) User clicks one block, which is supposed to be an edge of multiblock (for example top-let-nearest block)
2) User clicks the opposite block ( bottom-right-farthest block in the same example)
3) A tool  checks what blocks it was clicked. If it was clicked on Turbine Casing - it checks why turbine can't be build, if it was fission reactor, casing it checks why reactor can't be made, etc and prints it to the player, e.g. "123, 33,456: Edge of turbine must be built of turbine casing", "123, 45, 567: block inside of turbine can't be dirt"  etc
(And maybe even highlight in the world the position of invalid block like some multiblock mods do)

Rinse and repeat

### Describe alternatives you've considered

Instead of building from scratch,
build a design the internet [block by block](https://ftbwiki.org/Industrial_Turbine#Examplary_Structure) and hope you don't mess up. 

It feels like having an option to custom-built something defeats the purpose.

**Comment by pupnewfster** [comment]
Right click the casing witha  configurator
