### ISSUE TITLE
Stackable machines

### ISSUE THREAD

**Issue by jamesjimmy88** [mekanism/Mekanism-Feature-Requests#565]
### Describe the feature you'd like

I'd simply for machines to not have a stack size of 1; placing multiple of the same newly crafted machines is a massive pain.
This is just a blind guess, but I think machine stack sizes are still at 1 because increasing it in older versions would allow you to generate energy from nothing, since placing them in energy cubes would charge them all while costing enough energy to only charge one, thus allowing to endlessly generate energy by charging energy cubes. In the latest versions this is not possible simply because you can't put more than one item at a time in chargers, but nobody took the initiative to remove the limit on the stack size.
Unless I'm missing something this should be trivial to implement and would be a huge QoL for factory-sim packs.

**Comment by blockgoblin31** [comment]
I think it’s still not a thing because it won’t work for any machines that are placed and then broken, making it weirdly inconsistent

**Comment by jamesjimmy88** [comment]
That shouldn't happen unless you break machines that are currently working. If you have 20 idle crushers that are full on energy storage they will just stack.

**Comment by blockgoblin31** [comment]
yes, assuming they have the same side config

**Comment by jamesjimmy88** [comment]
They usually will, if you are playing a factory-sim pack. In regular packs most players won't even make more than a few of the same machine (if even more than one), and very few of them will pick them up while having more than one per type, since if you are placing multiples of the same machine it usually means that you picked a permanent spot for them. Just having the machines stack when newly crafted outweighs any potential inconsistency that could be found in those cases.
