### ISSUE TITLE
Define Infuse Types and Chemicals via JSONThings

### ISSUE THREAD

**Issue by SilverMedal02** [mekanism/Mekanism-Feature-Requests#568]
### Describe the feature you'd like

There is a nice mod by gigaherz called JSONThings that allows people to create "thingpacks", all-in-one packs that include a system to define items and fluids, along with a resource pack and datapack for them. Being able to define Infuse Types and Chemicals would be a very nice feature to have. Though, I don't know if Mekanism is able to have such compatibility, it may be purely on JSONThings' end.

### Describe alternatives you've considered

Obvious contenders are KubeJS and Crafttweaker, though I believe JSONThings deserves to be equal to them.

**Comment by pupnewfster** [comment]
This will be included in Mekanism for mc 1.20.1+ when that is eventually released (though I am not marking this as implemented yet as I still need to write some docs on how to use it)

**Comment by pupnewfster** [comment]
[Docs for it](https://github.com/mekanism/Mekanism/wiki/JsonThings-Integration) (once a 1.20 build is released)
