### ISSUE TITLE
Fission Reactor Coolant Capacity Cap

### ISSUE THREAD

**Issue by AVASSON** [mekanism/Mekanism-Feature-Requests#573]
### Describe the feature you'd like

Hello, I would like to ask, how to make the coolant capacity of the fission reactor exceed the upper limit of 2147483647 by modifying the source code?

**Comment by Jorue23** [comment]
That's not possible cause 2147483647 is the biggest possible integer in java.

**Comment by AVASSON** [comment]
But the upper limit of the long type is larger than this

**Comment by pupnewfster** [comment]
Yes but fluids use internet which is not changeable by us
