### ISSUE TITLE
Cable upgrades

### ISSUE THREAD

**Issue by AlexDe-v** [mekanism/Mekanism-Feature-Requests#574]
### Describe the feature you'd like

It would be really handy to have a cable upgrade item like we have with machines, it should be craftabe with alloys and maybe iron nuggets or something (corresponding to the tier). You could be able to right click a cable to upgrade it just like a machine or Ctrl + right click to use all your upgrades in your hand to an entire network of cables. For example if I have a 64 block long cable and I Ctrl + right click with a stack of ultimate upgrades it would turn all my 64 cables into ultimate ones.

Should also apply to tubes, pipes etc

### Describe alternatives you've considered

Break every cable, craft them into a better version and place each and every cable again.

### Additional context

It's always a tedious task to upgrade cables, especially when you grow out of your small base with basic cables and now need to feed the machines with more juice. But once you buried the cables and have everything connected it becomes a pain to replace everything really quickly. Would be really nice to just have this item where you can Ctrl + right click one thing and all of your cables are a tier higher.

**Comment by dorianbozicek** [comment]
Positive this is already available by right clicking the respective alloy on the cable you want to upgrade. And yes it works like you specified.

**Comment by AlexHgC** [comment]
Yes, it already exist. Right click with an alloy one tier higher to upgrade 8 cables, and if you have like 80 cables, you can right click 10 times on the same cable to upgrade others connected.

**Comment by AlexDe-v** [comment]
Thanks for the info! I will close this issue, tough maybe a info in the shift + n description of an alloy would be nice
