### ISSUE TITLE
protection from magic and weapons mods and normal vanilla thorns for the MekaSuit

### ISSUE THREAD

**Issue by GrubbyGamer** [mekanism/Mekanism-Feature-Requests#588]
### Describe the feature you'd like

more protection from other mods like timeless and classic guns or magic mods

### Describe alternatives you've considered

protect me when some1 shoot on me because its ignores the mekasuit armor or when thorns hit me i comes damage

**Comment by pupnewfster** [comment]
No, in regards to magic at least for the most part in released versions the inhalation purification unit allows for protection against magic damage (though I don't have a good solution for that currently in 1.20). In regards to damage types that other mods may mark as bypassing armor... we intentionally respect their wishes... Our API is written in such a way however, that if some addon wants to provide protection against more forms of damage they should be able to via a custom mekasuit unit.
