### ISSUE TITLE
Jetpack upgrade

### ISSUE THREAD

**Issue by Acat1234** [mekanism/Mekanism-Feature-Requests#599]
### Describe the feature you'd like

a elytra mode and it goes like Regular Hover Elytra Disabled

**Comment by pupnewfster** [comment]
No, it is an intentional decision we make players do to decide which they want to use. The “variant” that supports both jet pack and elytra (and jet pack acting as fireworks for the elytra) is the meka suit

**Comment by Acat1234** [comment]
oh
