### ISSUE TITLE
Add a way to filter the digital miner for a single block you do not have

### ISSUE THREAD

**Issue by ChillaxBro1** [mekanism/Mekanism-Feature-Requests#602]
### Describe the feature you'd like

Currently, there is sometimes no good way to filter for a specific block if you do not have the block you want to filter for and the block has no unique tags. This can be annoying when trying to find rare ores/blocks.

Two ideas on way this could be fixed:
1. Allow the current ItemStack filter to be set using items dragged from JEI like you currently can with the replacement filter
2. Add a new Block ID filter that uses a blocks already existing ID

### Describe alternatives you've considered

None of the existing filter can solve this problem 100% of the time
ItemStack - can't be populated with JEI so you need to already have the block, not useful for finding new blocks
Tag - not every block has any unique tags and only has tags like what it can be mined by, these generic tags can include far too many blocks you don't want
Mod ID - sometimes you want a specific block from a mod that has a lot of other blocks you don't want, cluttering the filter

**Comment by AlexHgC** [comment]
Already exist, on general.toml set "easyMinerFilters = false" to true so you can drag from JEI

**Comment by ChillaxBro1** [comment]
Oh, awesome. Thank you for letting me know!
