### ISSUE TITLE
QIO quality of life improvements

### ISSUE THREAD

**Issue by SmashinSkull** [mekanism/Mekanism-Feature-Requests#605]
### Describe the feature you'd like

It would be amazing if there was some more configuration for QIO, I've listed some features I'd love to see below.
The lack of these features is currently why I often use AE2 rather than QIO at the moment.

1. Being able to unfocus the search bar to be able to use "e" to exit the GUI
2. Having crafting windows spit the existing ingredients back into the system (rather than your inventory) when you replace with a new recipe.
3. Having the ability to keep crafting windows open when closing the GUI (maybe a toggle option to close or leave them)

**Comment by gtech0** [comment]
Agreed. Not being able to unfocus search bar is rather irritating.
