### ISSUE TITLE
Iron Golems and Snow Golems Should be Immune to Radiation

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism-Feature-Requests#608]
### Describe the feature you'd like

Just like how robits are immune to radiation, iron golems and snow golems should be as well, since they are made out of iron and snow. Radiation can't be lethal for them since there is no DNA to mutate.

**Comment by Ashwinaaaaaaahdt** [comment]
But the golem-making technique needs pumpkin which is biologically made
Snow golems must be fully immune as pumpkins can be sheared(removable)
But Iron Golem, the pumpkin is unremovable
Then iron golem isn't immune to radiation

**Comment by UnknownSerhan** [comment]
IMO pumpkin shouldn't be accounted for this because it just a block that converts them into the golem form. Iron golem's head is still made out of iron, not pumpkin.
