### ISSUE TITLE
Futurepack mod integration 

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mekanism/Mekanism-Feature-Requests#609]
### Describe the feature you'd like

This integration is about Futurepack and Mekanism
Like neon energy(future pack) to joules(mekanism) energy or vice-versa transformer
Fermentation barrel(future pack) transferring the biogas to a gas-burning generator(Futurepack or Mekanism) through a pressurized tube
Zinc(Futurepack) extraction by chemical dissolution
Removal of the ore-making recipe (it conflicts with Futurepack )
(make it available for 1.14x to 1.18x or at least 1.16.5 to 1.18x)

**Comment by Ashwinaaaaaaahdt** [comment]
> ### Describe the feature you'd like
> 
> This integration is about Futurepack and Mekanism
> Like neon energy(future pack) to joules(mekanism) energy or vice-versa transformer
> Fermentation barrel(future pack) transferring the biogas to a gas-burning generator(Futurepack or Mekanism) through a pressurized tube
> Zinc(Futurepack) extraction by chemical dissolution
> Removal of the ore-making recipe (it conflicts with Futurepack )
> make it available for 1.14.x to 1.18x
> ### Describe alternatives you've considered
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

**Comment by Ashwinaaaaaaahdt** [comment]
> ### Describe the feature you'd like
> 
> This integration is about Futurepack and Mekanism
> Like neon energy(future pack) to joules(mekanism) energy or vice-versa transformer
> Fermentation barrel(future pack) transferring the biogas to a gas-burning generator(Futurepack or Mekanism) through a pressurized tube
> Zinc(Futurepack) extraction by chemical dissolution
> Removal of the ore-making recipe (it conflicts with Futurepack )
> (make it available for 1.14x to 1.18x or at least 1.16.5 to 1.18x)
> ### Describe alternatives you've considered
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

Can you make this thing possible

**Comment by thiakil** [comment]
We are no longer developing for such old versions.

Some of those integrations can be done by future pack though as they're just recipes

**Comment by Ashwinaaaaaaahdt** [comment]
> We are no longer developing for such old versions.
> 
> Some of those integrations can be done by future pack though as they're just recipes

Is 1.18.2 mekanism abandoned in terms of development 
Because like mekasuit's oxygen generator won't work even underwater in the asteroid belt(space) so can you make it possible by staying underwater would make it breathable 
But staying outside water would make player suffocate

**Comment by thiakil** [comment]
> Is 1.18.2 mekanism abandoned in terms of development

Correct

**Comment by Ashwinaaaaaaahdt** [comment]
> > Is 1.18.2 mekanism abandoned in terms of development
> 
> Correct 

So I will close the issue as not planned until the new update of futurepack comes out

**Comment by Ashwinaaaaaaahdt** [comment]
Okay what about 2 things which are ignored 

Like xp storage and labs

Labs https://github.com/mekanism/Mekanism-Feature-Requests/issues/531#issuecomment-2055349013_

Xp storage 
https://github.com/mekanism/Mekanism-Feature-Requests/issues/544#issuecomment-2055360143_

**Comment by thiakil** [comment]
They look like standalone requests to me? If we decide to implement them, they'd be done on whatever the latest minecraft version is at the time

**Comment by Ashwinaaaaaaahdt** [comment]
> They look like standalone requests to me? If we decide to implement them, they'd be done on whatever the latest minecraft version is at the time

Mekanism lacks any structure to make them interesting mod
So the structure makes mekanism a bit more popular as it gives more ideas to explore instead of staying at same chunk

**Comment by Ashwinaaaaaaahdt** [comment]
And there is a feature already planned for adding xp upgrade for electric furnace as the dev have said in past issue about electric furnace bug
