### ISSUE TITLE
EU energy support (IC2 Classic/Industrial Reborn)

### ISSUE THREAD

**Issue by NospamNospam** [mekanism/Mekanism-Feature-Requests#610]
### Describe the feature you'd like

Mekanism is said to support EU energy, but in fact it doesn't. Please add this.

**Comment by cplir-c** [comment]
[Related issue about the EU tooltip](https://github.com/mekanism/Mekanism-Feature-Requests/issues/622)

**Comment by NospamNospam** [comment]
- When a feature that is not actually supported is listed in the wiki and asked to be added, your solution?
- Remove the wiki reference!
- Bravissimo!

**Comment by thiakil** [comment]
The mod we supported is not in current versions of minecraft, we never promised to support any and every IC2 clone (others didnt exist when the feature was added)

I thought that was the point of this feature request, to add support for them lol

**Comment by NospamNospam** [comment]
Yes, lol, indeed. I added your mod to my server just for this conversion and the walkie talkie, both don't work. Trolololololo, I'd say.
