### ISSUE TITLE
[1.18.2] Please backport safety mode for free runner....

### ISSUE THREAD

**Issue by zeng-github01** [mekanism/Mekanism-Feature-Requests#611]
### Describe the feature you'd like

Why don't you guys try porting it to 1.18.2? It doesn't look difficult, just needs to modify a few lines of code.

**Comment by thiakil** [comment]
we dont develop on old versions, but PRs can sometimes be accepted (whether we release it or not is another question)

**Comment by zeng-github01** [comment]
> we dont develop on old versions, but PRs can sometimes be accepted (whether we release it or not is another question)

Then I try to submit a PR? However, I couldn't find the default language file for English, so I only filled in the Chinese text. Can you help me fill it in? (e.g:"free_runner.mekanism.safety": "安全性(safety)",)
