### ISSUE TITLE
Gauge dropper capacity

### ISSUE THREAD

**Issue by H4ckerxx44** [mekanism/Mekanism-Feature-Requests#614]
### Describe the feature you'd like

It would be cool to be able to adjust the gauge dropper capacity with a config as a lot of other capacities are adjustable

### Describe alternatives you've considered

Turn the gauge dropper into a "basic" "advanced" "elite" "ultimate" thing, each stage has more capacity than the previous one

**Comment by pupnewfster** [comment]
This was implemented as part of 10.5.0
