### ISSUE TITLE
Salt Block -> 4 Salt Crafting Recipe

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [mekanism/Mekanism-Feature-Requests#621]
### Describe the feature you'd like

Add a crafting recipe converting 1 salt block into 4 salt.

### Describe alternatives you've considered

Simply break the salt block; HOWEVER, this leads to incompatibility with compacting drawers.

### Additional context

A crafting recipe would allow compacting drawers to support salt, which would be extremely useful for compact salt storage.

**Comment by UnknownSerhan** [comment]
Clay block doesn’t have a recipe for that so why should salt do? Also salt is very rarely used, it is not a viable option to use it in huge setups.

**Comment by pupnewfster** [comment]
I agree, in many ways salt is similar to clay, I don't think there is a reason to allow in crafting directly. Especially as for other 2x2 "storage" blocks like quartz vanilla doesn't tend to allow just directly uncrafting
