### ISSUE TITLE
Change spelling of "whoosh" (at least in American English)

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [mekanism/Mekanism-Feature-Requests#623]
### Describe the feature you'd like

This is a weird thing to point out, but in Minecraft itself, "whooshes" is spelled with two <i>h</i>s in the captions, but Wind Turbines in Mekanism have only one _h_ in its spelling: _woosh_.

### Describe alternatives you've considered

Turn off captions or just ignore the spelling difference.

**Comment by pupnewfster** [comment]
Google failed me, I wasn't sure if it was even a word, or how to spell it, but it shows as a word (because of the UK) without the `h` so I just assumed that was right, even though it looked weird.
