### ISSUE TITLE
Facades, Covers, etc

### ISSUE THREAD

**Issue by BrandonJ98** [mekanism/Mekanism-Feature-Requests#626]
### Describe the feature you'd like

Yes I know it's a duplicate. A lot of people have been asking for facades/covers/hollow casings to disguise cables for years. I'm shocked it hasn't been done yet. No other mod that I've seen in newer versions (1.16+) can hide them, and it looks bad to have holes into the wall/floor to run these pipes through. 

### Describe alternatives you've considered

Haven't found any yet in months of searching.

### Additional context

Just cable covers or mimic/ghost blocks to plug the holes around cables when people run them through walls or into the floor. Similar to XNet or AE facades (which unfortunately aren't compatible with Mekanism pipes).

**Comment by BrandonJ98** [comment]
For those who would like to suggest Chisel & Bits, that has been taken over in at least 1.20 by Rechiseled, which does not have the bits/miniature blocks.

**Comment by Xebakyr** [comment]
What? Rechiseled has NOT taken over Chisel & Bits. Chisel and Bits is still (to my knowledge) being updated, and is intended to serve and entirely different purpose and is made by a completely different author. The mods have nothing in common and Rechiseled has existed for a while as a mod to add extra blocks - NOT as a replacement for C&B

**Comment by pupnewfster** [comment]
Please don’t open intentionally duplicate issues
