### ISSUE TITLE
Support for `PreventRemoteMovement` in MekaSuit Boots

### ISSUE THREAD

**Issue by MuteTiefling** [mekanism/Mekanism-Feature-Requests#630]
### Describe the feature you'd like

Would be nice if the MekaSuit Magnet Boot upgrade would respect the `PreventRemoteMovement` flag on items and not suck them up. 

### Additional context

Here's a post from BluSunrize requesting the same feature of another mod with magnets, including links to relevant repos

> Items with the Magnet enchant as well as the magnet block allow picking up Item entities that have the NBT Tag "PreventRemoteMovement" applied.
This tag is (for instance) applied by Immersive Engineering's conveyor belts.

> This NBT Tag on Item entities has established itself in the modding community as a global flag for "don't magnet that!"
It was originally hashed out between Vazkii, Ellpeck, WayOfTime, myself and a few others. We agreed on PreventRemoteMovement.
I made my conveyors apply that tag, and various devs adjusted their magnet to ignore entities tagged as such.

> For example implementation see here:
https://github.com/Draconic-Inc/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/items/tools/Magnet.java#L73-L75
https://github.com/SuperMartijn642/SimpleMagnets/blob/forge-1.19/src/main/java/com/supermartijn642/simplemagnets/MagnetItem.java#L71

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/177#issuecomment-767627407

**Comment by MuteTiefling** [comment]
Ah, fair enough :D Thanks!
