### ISSUE TITLE
Tag Extraction From Item Name for Filters

### ISSUE THREAD

**Issue by SoccPuppet** [mekanism/Mekanism-Feature-Requests#635]
### Describe the feature you'd like

It would be more convenient if while adding a tag filter, an item name could be given to have all its tags listed out. This would make it far easier to filter for the right item even if you don't have one on hand. For an existing implementation, see Sophisticated Backpack, as their filter allows one to choose tags from an item. 

### Additional context

About 30% of questions we see on the discord is about what tag to use to filter for this thing in the digital miner

**Comment by pupnewfster** [comment]
If you make a dictionary item from mekanism you can drag items into the target slot from JEI to view their tags of various types (including block tags, which is what the digital miner uses). I am not sure how much benefit this would have, especially as users already get confused and think they can use item names as tags.

**Comment by SoccPuppet** [comment]
I suppose I specified item name because the dictionary still requires you to have the block already on hand, but you're also quite right in that users get confused about tags anyways. Perhaps eventually changing the tag filter to only allow tag extraction like this to set the filter, so that it's clear you can't just use the item name?

**Comment by pupnewfster** [comment]
No, the dictionary gui allows you to click and drag from jei to see the names of all sorts of things including fluids and chemicals.
