### ISSUE TITLE
Quick Swap / Upgrade Pipes with higher tiers

### ISSUE THREAD

**Issue by James-P-Bennett** [mekanism/Mekanism-Feature-Requests#636]
### Describe the feature you'd like

I am seeking a functionality that enables swift replacement of various types of pipes, like mechanical or pressurized universal cables, with higher-tier counterparts without the necessity of breaking and reinstalling them, along with the hassle of reconfiguring every input/output, color filter, and so forth. 

### Describe alternatives you've considered

I looked everywhere on the website, wiki and discord for a means to do this and it doesn't seem possible. 

### Additional context

For instance, if I'm inspecting a standard universal cable while holding an advanced universal cable, It'd be much more convenient to be able to "upgrade" it in place while keeping all it's configurations, very similar to how tier installers work for machines.

**Comment by pupnewfster** [comment]
Right click them with the next tier of alloy, it does up to eight at a time
