### ISSUE TITLE
Add a logistical sorter side option into machines

### ISSUE THREAD

**Issue by PyroFlareX** [mekanism/Mekanism-Feature-Requests#643]
### Describe the feature you'd like

With a machine upgrade module for logistical sorting, add a way to filter inputs in machines directly.

### Describe alternatives you've considered

Using a ton of logistical sorters

### Additional context

Filtering is a pain.

**Comment by pupnewfster** [comment]
Are you perhaps looking for the existing transporter config tab?

**Comment by PyroFlareX** [comment]
No, that only sorts for existing colors assigned to items going through the pipes. The color system is hard to work with and requires an effective buffer. I'm suggesting adding a upgrade (like the speed or energy one) that allows a machine to filter what it allows for input directly. It's difficult do make dense setups without some form of item/fluid/chemical filter.

**Comment by thiakil** [comment]
That already exists tho, is what we're saying. The transporter tab can restrict what colour is input (strict) and what colour is output

**Comment by PyroFlareX** [comment]
Yeah but the color system requires a bulky setup which makes it difficult to use. Furthermore, each source requires a logistical transporter to set the color if it comes from storage, which isn't ideal for use with drawers for instance. I'm suggesting this because the color system is very limited and difficult to use, rather than trying to use it, a filter system like how you can filter the digital miner and logistical sorter is more useful for compact automation capabilities.

**Comment by thiakil** [comment]
No, the colour system does not require any colour on a cable
