### ISSUE TITLE
Allow muffling upgrades on Chargepad and Robit QOL Change

### ISSUE THREAD

**Issue by Baylem** [mekanism/Mekanism-Feature-Requests#645]
### Describe the feature you'd like

I would like to see muffling upgrades be useable on the Chargepad, as the sound is very obnoxious, especially in packs without sound mufflers. 

Also, within the mod itself, it is very taxing to hear a constant Chargepad when a fully charged Robit is at it's home. Is it possible to not have the chargepad make sound when it is assigned a Robit and it is fully charged.

**Comment by thiakil** [comment]
honestly I think it should just have its sound removed entirely lol
