### ISSUE TITLE
[Suggestion] Jetpack Change

### ISSUE THREAD

**Issue by xWaller0119** [mekanism/Mekanism-Feature-Requests#649]
### Describe the feature you'd like

Add forward velocity to the jetpack. Trying to fly with it and having the upward velocity pretty fast but no forward velocity is VERY annoying. It feels like you move nowhere but up and down with it half the time cause it's so slow traveling.

**Comment by Ashwinaaaaaaahdt** [comment]
> ### Describe the feature you'd like
> 
> Add forward velocity to the jetpack. Trying to fly with it and having the upward velocity pretty fast but no forward velocity is VERY annoying. It feels like you move nowhere but up and down with it half the time cause it's so slow traveling.
> 
> ### Describe alternatives you've considered
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

There is toggle for jetpack
That is hover

**Comment by pupnewfster** [comment]
This was done in 1.20.4 already
