### ISSUE TITLE
Usage for spent nuclear waste

### ISSUE THREAD

**Issue by mrsmile1919** [mekanism/Mekanism-Feature-Requests#658]
### Describe the feature you'd like

The spent nuclear waste is kind of useless and it just waste space so there should be a way to get rid of it,  so it should be processable in the isotopic centrifuge into dirty lead slurry, because all nuclear waste from irl fission reactiors should eventually decay mostly into lead, I think It'd be a good way to get rid of all of those barrels of that waste, instead of wasting space for it, and the fact that it "decays" doesn't really help considering that again, it still requires space to contain that and the decay is... just not fast enough if you produce a lot of plutonium and polonium unless you once again, have a lot of barrels.

### Describe alternatives you've considered

Alternatively it could be used in the electrolytic separator in order to make the dirty uranium slurry and dirty lead slurry, in a 1:3 ratio between uranium and lead slurry.

**Comment by USMP-lancer** [comment]
thats kinda hte point of spent nuclear  waste, you already seperated the useful part, what remains is hte trash you cant use
