### ISSUE TITLE
Quantum Entangloporter NBT/Stackable?

### ISSUE THREAD

**Issue by ShadwDrgn** [mekanism/Mekanism-Feature-Requests#665]
### Describe the feature you'd like

It would be great if the QEs stacked. having several ready in a bag means taking up a large amount of that bags space. My guess would be that this is currently not allowed because each has some kind of ID or nbt data  that is unique attached to it. It would be GREAT if that data weren't put on it until it's placed inthe world and then could be cleared by crafting it in your grid alone so it can stack again.

SO many 1.20.1 mods seem to have machines that can never stack it's REALLY killing my inventory management.

**Comment by UnknownSerhan** [comment]
The stacking feature got implemented in 1.20.4, I wouldn't expect for a backport.

**Comment by ShadwDrgn** [comment]
Thanks for the ABSURDLY fast reply.
