### ISSUE TITLE
Add a machine that receives infuse types and ejects them as fluids

### ISSUE THREAD

**Issue by lsalazarm99** [mekanism/Mekanism-Feature-Requests#672]
### Describe the feature you'd like

I would like a machine that receives infuse types (like enriched redstone) and ejects them as fluids. This way, we can store the fluid in a chemical tank or any other storage system without manually using a gauge dropper in a metallurgic infuser.

### Describe alternatives you've considered

As said, you can use a gauge dropper in a metallurgic infuser in order to extract the fluid that the machine produces when you insert an infuse type. But the process can't be automated.

### Additional context

I faced this requirement when I was trying to automate in AE2 the creation of something that requires infuse types in the metallurgic infuser. Right now you need to input the materials (the item to be infused, and the infuse type) in two separate locations of the machine because you have to input two different items.

The machine already has an input for infuse types so both this and the items could be inserted from the same side of the machine. But right now there is no way to automatically produce an infuse type as a fluid.

This limitation makes the setup for this machine less intuitive and more complex.

**Comment by pupnewfster** [comment]
Set a tube to extract to forcefully pull out of a metallurgic infuser where the infuse type side config has that side set to output. This has been a thing since Mekanism 10.1

**Comment by lsalazarm99** [comment]
Wow! Didn't know about that. I searched about this but didn't find anything. Sorry to bother you and thanks for this tip!
