### ISSUE TITLE
Mixing blue and yellow pigments to make green

### ISSUE THREAD

**Issue by Shwift-bit** [mekanism/Mekanism-Feature-Requests#690]
### Describe the feature you'd like

Blue and yellow should make green pigment in the pigment mixer. I am unsure if there are other colors with this problem but its the one i noticed.

### Describe alternatives you've considered

The only way to get green pigment or dye is from cactuses and flowers. Itd be nice if the pigment mixer could actually mix the two primary colors.

**Comment by kienerxyzzy** [comment]
Also cyan/light blue with yellow for lime green
