### ISSUE TITLE
Idea: Uranium Processing Overhaul

### ISSUE THREAD

**Issue by kienerxyzzy** [mekanism/Mekanism-Feature-Requests#693]
### Describe the feature you'd like

You centrifuge Uranium into U235 and U238, which U235 turns into fuel. Later on, you get Polonium and can use that to fire a neutron at U238(polonium can radiate stray neutrons), which turns it into Pu239, which can be used as fuel, as well as to make Plutonium Pellets.

### Additional context

I am not a scientist and all this information has come from a Veritasium video.

<sub>I am not affiliated with Veritasium in any way.</sub>

**Comment by kienerxyzzy** [comment]
I closed it myself, too game-changing

**Comment by Ashwinaaaaaaahdt** [comment]
> I closed it myself, too game-changing

Try to "closed it as not planned", otherwise it is seen as "closed as completed"
