### ISSUE TITLE
Meka-suit protection unit

### ISSUE THREAD

**Issue by TiFixZ** [mekanism/Mekanism-Feature-Requests#694]
### Describe the feature you'd like

Hello. If you are a mekanism mod developer, can you help? I think you know that one of the most popular mods that comes with Mekanism is Draconic Evolution. Unfortunately, I was unable to contact the developer of Draconic Evolution( So I decided to write to you. In version 1.18.2, the damage of "Guardian of Chaos" was kinetic, and in version 1.20.1, apparently, it was replaced with something else. The Meka-Suit armor only protects against kinetic damage. What are the chances that you can implement an idea, for example, with a new module that would protect against any type of damage, but would be very expensive to produce? I hope you can implement this idea)

Thank you for uniting the Minecraft community for so long🤍

My English is bad(

**Comment by pupnewfster** [comment]
No, we intentionally don't block any damage types that are marked as bypassing armor. That doesn't prevent some addon from making an addon adding support for this, but we won't do so natively.
