### ISSUE TITLE
Muffling upgrade on gas-burning generator

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism-Feature-Requests#70]
Please o please... it drives me crazy, give me a way to make it quiet XD

**Comment by rodrigokiller** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/93
you can close this issue :)

**Comment by pupnewfster** [comment]
I closed the other one as this one is the older of the two, this is the one I am leaving open to track it.
