### ISSUE TITLE
Sealed (Full Block) cables / pipes

### ISSUE THREAD

**Issue by Kevadroz** [mekanism/Mekanism-Feature-Requests#711]
### Describe the feature you'd like

Add some form of sealed (full block) cables / pipes for situations where you need to get energy, fluids, etc. into an airtight / sealed space.

This is mostly for space mods where you need to create sealed rooms to get a room with breathable air.

### Describe alternatives you've considered

Maybe add a feature to camouflage cables with a block? That way if a cable is camouflaged as a full block it could be considered "sealed". It's more work tough.

### Additional context

I'm making a modpack with mekanism and ad astra, and I can't wire energy cables to a sealed space because of the mentioned issue.

Quantum Entangloporters are too overkill, costly and late-game to be a replacement.

**Comment by Jorue23** [comment]
Maybe use energy cubes as a sort of passthrough?

**Comment by Kevadroz** [comment]
> Maybe use energy cubes as a sort of passthrough?

Energy cubes are not visually solid, and in my case ad astra doesn't detect them as solid, I could add them to the whitelist, but again, not visually solid and sealed cables is a better solution.

**Comment by tolomea** [comment]
I wonder how hard this would be as a third party add on mod.

**Comment by Kevadroz** [comment]
> I wonder how hard this would be as a third party add on mod.

![2024-09-29_23 20 46](https://github.com/user-attachments/assets/3963b356-a645-43c8-b2ee-ea14abff57ee)
About 2 days of work lmao. Tough this isn't for an addon but rather for a modpack, I may make an addon in the future.

EDIT: nvm, [someone was faster than me](https://modrinth.com/mod/mekanism-covers).

**Comment by Kevadroz** [comment]
I'm going to close this since with the existence of the addon I mentioned above this issue is solved, however official support would still be nice.
