### ISSUE TITLE
Full block sized universal cable.

### ISSUE THREAD

**Issue by tolomea** [mekanism/Mekanism-Feature-Requests#713]
### Describe the feature you'd like

Could you add full blocks sized versions of the universal cables?

I know there's been talk of facades in the past and I imagine those are a huge amount of work to implement.
Visually the biggest problem with not having them is holes in walls.
I've been using energy cubes to plug those holes, which works but is rather overkill.
That got me wondering if you could add block sized versions of the energy cables, aka a cheaper near zero capacity energy cube.
It's not as pretty as facades but I'd imagine way easier to implement and makes the hole in wall part of this go away.

**Comment by Kevadroz** [comment]
This is basically the same as #711
