### ISSUE TITLE
Be able to customize mekasuit and mekatool colors, etc

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism-Feature-Requests#72]
Basically this would add an additional upgrade for all meka components, this upgrade could be made using various dyes and parts. This upgrade would allow you to select a different color for the mekasuit and it's parts in their upgrade configurations. I would really like to see a black version of the suit personally.

**Comment by Peekofwar** [comment]
Perhaps this could even be a separate coloring paint station block which you would insert supported items/tools and use a GUI interface to mix dyes together to make certain colors... Perhaps the Mekasuit should have a primary color, and a secondary color that can be modified. Would be cool if certain components like solar panels and the helmet visor could also be tinted.
