### ISSUE TITLE
Ad astra meka suit air support

### ISSUE THREAD

**Issue by plakiiskute** [mekanism/Mekanism-Feature-Requests#731]
### Describe the feature you'd like

So basically it would be nice if I could use the Meka suit as a space suit instead so like a space module

### Describe alternatives you've considered

Although you could just make the suit not need air if your in it

**Comment by thiakil** [comment]
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon

**Comment by plakiiskute** [comment]
Thanks
