### ISSUE TITLE
Industrial alarms configurable range?

### ISSUE THREAD

**Issue by chardo440** [mekanism/Mekanism-Feature-Requests#84]
**Describe the feature you'd like**
Back in ic2 nuclear control, you could change the range at which the alarm could be heard. This was extremely helpful for when you were at the other side of your base and stuff started to go wrong. Right now it feels like it's at 8 blocks

**Describe alternatives you've considered**
GUI or config. Either would be awesome. or Redstone conduits so we could stack multiple alarms around the base without using redstone dust.

**Additional context**

**Comment by pupnewfster** [comment]
For 10.1 I am [upping](https://github.com/mekanism/Mekanism/commit/db1691083f08da17e1ead197cc7f868e089548f7) the default range from 16 to 128. But either way I am closing this issue just given the range is already configurable by adjusting the sounds.json using a resource pack.
