### ISSUE TITLE
Make nutrient past a liquid 

### ISSUE THREAD

**Issue by Thomasina21** [mekanism/Mekanism-Feature-Requests#90]
It doesn't make sense that nutrient past is a gas. and I want to see my dynamic tank fill up.

**Comment by pupnewfster** [comment]
I will leave this open but you can put it in your dynamic tank regardless.

**Comment by pupnewfster** [comment]
At least for now this is not happening, I did at some point though change the canteen when empty to just say empty instead of no gas though.
