### ISSUE TITLE
API Access to owner UUID or owner UUID passed to FakePlayer [MekV10]

### ISSUE THREAD

**Issue by Caltinor** [mekanism/Mekanism-Feature-Requests#92]
**Describe the the feature you'd like**
I develop a protection mod, and would like to be able to check when the Pump and Digital Miner interact with the world if their owners are permitted to do so.  The ideal solution for general compatibility is to have the `FakePlayer` UUID match the owner, but as I read in other issues mekanism is not really setup for that.  My alternative suggestion is to add access in the API to the TE owner so that at least compat for mekanism can be built in which calls that information when my mod needs it.

**Describe alternatives you've considered**
see above

**Additional context**
Specific to my mod,  ownership of land is held at the level of the "Guild" a player is a member of.  My protection checks involve getting the owning guild of the region of the block being interacted with and checking if the event PlayerEntity is a member.  If the latter/alternate solution is implemented, I would simply add logic to check if the breaking player is the mekanism FakePlayer and if true use the API to get the owner to then pass as the event entity.

**Comment by pupnewfster** [comment]
Closing this as of 10.0.12 and https://github.com/mekanism/Mekanism/pull/6607 we have started simulating the UUID of the fake player as the player who is the owner.
