### ISSUE TITLE
JEI-enabled crafting grid on the QIO dashboard

### ISSUE THREAD

**Issue by ArtyFarty0108** [mekanism/Mekanism-Feature-Requests#94]
**Describe the the feature you'd like**
An upgrade to the dashboard that implements a JEI enabled crafting grid in the dashboard would be incredibly helpful! A wireless variant would also be very impressive.

**Describe alternatives you've considered**
I currently place the dashboard directly above my crafting table to streamline the crafting process. 

**Additional context**
I'm trying to remove refined storage from my mod list as Mekanism already has an awesome and better executed disk based storage system, this one missing feature makes it difficult to fully convert.

Huge fan of this mod and all its authors, thanks so much for all your hard work! Best wishes to everyone during the pandemic!

**Comment by pupnewfster** [comment]
We are already planning our own spin on the "crafting grid" style system as I previewed how it may look on our discord https://discordapp.com/channels/554379889122213888/665380539892498442/733778565383979058 though this is still probably a decent ways off as beyond just trying to get a sense of how it might look I haven't really spent any time yet on V10.1
